python_sources = [
'__init__.py',
'test_trj.py',
'test_tng.py',
'test_timestep_api.py',
'test_pqr.py',
'test_pdbqt.py',
'test_null.py',
'test_netcdf.py',
'test_namdbin.py',
'test_mol2.py',
'test_mmtf.py',
'test_memory.py',
'test_h5md.py',
'test_gsd.py',
'test_gro.py',
'test_gms.py',
'test_fhiaims.py',
'test_dms.py',
'test_dlpoly.py',
'test_crd.py',
'test_copying.py',
'test_chemfiles.py',
'test_chainreader.py',
'test_amber_inpcrd.py',
'reference.py',
'base.py',
'test_xyz.py',
'test_writer_registration.py',
'test_writer_api.py',
'test_windows.py',
'test_txyz.py',
'test_trz.py',
'test_xdr.py',
'test_pdb.py',
'test_trc.py',
'test_dcd.py',
'test_tpr.py',
'test_lammps.py',
'test_reader_api.py',
]

py3.install_sources(
  python_sources,
  subdir: 'MDAnalysisTests/coordinates'
)
