python_sources = [
'2lyz_gmx_2019-beta3.tpr',
'2lyz_gmx_2018.tpr',
'2lyz_gmx_2016.tpr',
'2lyz_gmx_2021.tpr',
'2lyz_gmx_2020.tpr',
'2lyz_gmx_2020_double.tpr',
'2lyz_gmx_2020-beta2.tpr',
'2lyz_gmx_4.0.tpr',
'2lyz_gmx_4.0.7.tpr',
'2lyz_gmx_4.0.6.tpr',
'2lyz_gmx_4.0.5.tpr',
'2lyz_gmx_4.0.4.tpr',
'2lyz_gmx_4.0.3.tpr',
'2lyz_gmx_4.0.2.tpr',
'2lyz_gmx_2023.tpr',
'2lyz_gmx_2022-rc1.tpr',
'2lyz_gmx_2021_double.tpr',
'2lyz_gmx_5.1.tpr',
'2lyz_gmx_5.0.5.tpr',
'2lyz_gmx_5.0.4.tpr',
'2lyz_gmx_5.0.2.tpr',
'2lyz_gmx_4.5.tpr',
'2lyz_gmx_4.5.5.tpr',
'2lyz_gmx_4.5.4.tpr',
'2lyz_gmx_4.5.3.tpr',
'2lyz_gmx_4.5.2.tpr',
'2lyz_gmx_4.5.1.tpr',
'ab42_gmx_4.6.1.tpr',
'ab42_gmx_4.6.tpr',
'drew_gmx_4.5.5.double.tpr',
'2lyz_gmx_2024.tpr',
'2lyz_gmx_2024_4.tpr',
'ala_nnpot_gmx_2025_0.tpr',
'2lyz_gmx_2025_0.tpr',
]

py3.install_sources(
  python_sources,
  subdir: 'MDAnalysisTests/data/tprs'
)

subdir('all_bonded')
subdir('virtual_sites')
