#!/usr/bin/env bash
#
# Written by Lily Wang, 2020
#
# This script is placed into the Public Domain using the CC0 1.0 Public Domain
# Dedication https://creativecommons.org/publicdomain/zero/1.0/
#
#
# NOTE: IF YOU RUN THIS SCRIPT YOU MUST BE ABLE TO COMPLY WITH THE DSSP
#       LICENSE BELOW.
#
# Boost Software License - Version 1.0 - August 17th, 2003 
# Permission is hereby granted, free of charge, to any person or organization 
# obtaining a copy of the software and accompanying documentation covered by 
# this license (the "Software") to use, reproduce, display, distribute, execute, 
# and transmit the Software, and to prepare derivative works of the Software, 
# and to permit third-parties to whom the Software is furnished to do so, all 
# subject to the following:

# The copyright notices in the Software and this entire statement, including 
# the above license grant, this restriction and the following disclaimer, 
# must be included in all copies of the Software, in whole or in part, and all 
# derivative works of the Software, unless such copies or derivative works are 
# solely in the form of machine-executable object code generated by a source 
# language processor.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
# FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT 
# SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR 
# ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, ARISING 
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
# IN THE SOFTWARE. 
# 
#
# Install DSSP from https://swift.cmbi.umcn.nl/gv/dssp/
#
# arguments
#    OSNAME : linux | darwin
#    PREFIX : "path/to/installdir"
#
# PREFIX can be relative to CWD or an absolute path; it will be created
# and DSSP unpacked under PREFIX (the tar file contains "dssp-xx.xx.xx/...")
#
#


set -o errexit -o nounset

SCRIPT=$(basename $0)


DOWNLOAD_URL='https://github.com/cmbi/dssp/archive/3.1.4.tar.gz'
TARFILE='3.1.4.tar.gz'


# path to dir with executables in the current HOLE distribution
DSSP_EXE_DIR=dssp-3.1.4

function die () {
    local msg="$1" err=$2
    echo "[${SCRIPT}] ERROR: $msg [$err]"
    exit $err
}

function is_native_executable () {
    local filename="$1" OSNAME="$2"
    file "${filename}" | grep -qi ${OFORMAT}
    return $?
}

OSNAME="$1"
case "$OSNAME" in
    Linux|linux)
	OSNAME=Linux
	OFORMAT=Linux
	;;
    OSX|osx|Darwin|darwin)
	OSNAME=Darwin
	OFORMAT="Mach-O"
	;;
    *)
	die "OS '${OSNAME}' not supported." 10;;
esac


PREFIX="$2"
test -n "$PREFIX" || die "missing argument PREFIX (installation directory)" 10

#------------------------------------------------------------
# start installation
#------------------------------------------------------------

mkdir -p "$PREFIX" && cd "$PREFIX" || die "Failed to create and cd to $PREFIX" 1
if ! test -f ${TARFILE}; then
    echo "Downloading ${TARFILE} from ${DOWNLOAD_URL}..."
    # fixing curl on travis/anaconda, see http://stackoverflow.com/a/31060428/334357
    export CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
    curl -L ${DOWNLOAD_URL} -o ${TARFILE} || \
    die "Failed to download ${TARFILE} from ${DOWNLOAD_URL}" 1
fi

# only install the executables in DSSP_EXE_DIR 
tar xvf ${TARFILE} ${DSSP_EXE_DIR} || die "Failed 'tar xvf ${TARFILE} ${DSSP_EXE_DIR}'" 1

MDA_DSSP_BINDIR="${PWD}/${DSSP_EXE_DIR}"
DSSP_EXE="${MDA_DSSP_BINDIR}/mkdssp"

cd $MDA_DSSP_BINDIR

echo "Configuring"
./autogen.sh
./configure
echo "Making"
make

test -f "${DSSP_EXE}" || die "mkdssp executable ${DSSP_EXE} not installed" 2
is_native_executable ${DSSP_EXE} ${OFORMAT} || \
    { file ${DSSP_EXE}; \
      die "${DSSP_EXE} will not run on ${OSNAME} (object format ${OFORMAT})" 3; }

echo "mkdssp was installed into ${MDA_DSSP_BINDIR}"
echo ">>> export PATH=\${PATH}:${MDA_DSSP_BINDIR}"

# repeat this line in .travis.yml
export PATH=${PATH}:${MDA_DSSP_BINDIR}
