python_sources = [
'chainIDnewres.pdb.gz',
'gromacs_ala10.top',
'fullerene.pdb.gz',
'1osm.pdb.gz',
'argon_npt_compressed.gro.gz',
'6QYR.mmtf.gz',
'5KIH.mmtf.gz',
'test.edr',
'single_frame.edr',
'bad_num_col.xvg',
'test.xvg',
'test_lowf.xvg',
'test_highf.xvg',
'molecule.sdf',
'1grm_elNemo_mode7.pdb.bz2',
'6msm.pdb.bz2',
'2r9r-1b.xyz.bz2',
'C12x64.xml.bz2',
'bigbox.gro.bz2',
'model_then_cryst.pdb.gz',
'cryst_then_model.pdb.bz2',
'cryst_then_model.pdb.gz',
'cobrotoxin_protein_forces.xvg.bz2',
'model_then_cryst.pdb.bz2',
'surface.pdb.bz2',
'tyrosol.pdbqt.bz2',
'testENT.ent',
'atomtypes.itp',
'atomtypes_charge.itp',
'edited_itp.itp',
'itp_nomass.itp',
'gromacs_ala10.itp',
'tip5p.itp',
'spce.itp',
'no_endif_spc.itp',
'cobrotoxin.h5md',
'cu_malformed.h5md',
'cu.h5md',
'1ubq-less-optional.mmtf',
'173D.mmtf',
'3NJW-onlyrequired.mmtf',
'fhiaims.in',
'pdbqt_inputpdbqt.pdbqt',
'1A2C.pqr',
'adk_open.pqr',
'adk_closed.dms',
'adk_closed_no_segid.dms',
'adk_closed_domains.dms',
'adk_open.coor',
'adk_oplsaa.trr',
'cobrotoxin.trr',
'surface.trr',
'trr_test_only_10_frame_10_atoms.trr',
'19hc.pdb.gz',
'helanal_bending_matrix_AdK_DIMS_H8_frames10to79.dat',
'helanal_bending_matrix_AdK_DIMS_H8.dat',
'1a28.pdb.gz',
'test.fasta',
'2r9r-1b.xyz',
'five.xyz',
'mini.xyz',
'adk_open.crd',
'1hvr.pdb',
'1grm_single.pdb',
'A6PA6_alpha.pdb',
'5digitResid.pdb',
'5a7u.pdb',
'4E43.pdb',
'SINGLECONECT.pdb',
'RANDOM_WALK_TOPO.pdb',
'CONECT2TER.pdb',
'adk_closed.pdb',
'adk_open.pdb',
'adk_oplsaa.pdb',
'align.pdb',
'charges.pdb',
'cobrotoxin.pdb',
'elements.pdb',
'cryst_then_model.pdb',
'conect_parsing.pdb',
'conect_error.pdb',
'cobrotoxin_dry_neutral_0.pdb',
'incomplete.pdb',
'namd_cgenff.pdb',
'model_then_cryst.pdb',
'sameresid_diffresname.pdb',
'pdbqt_querypdb.pdb',
'nucl_res.pdb',
'nmr_neopetrosiamide.pdb',
'water_methane_acetic-acid_ammonia.pdb',
'varying_occ_tmp.pdb',
'unordered_res.pdb',
'xl_serial.pdb',
'adk_open_10res.pdb',
'adk_oplsaa.tpr',
'aux_edr.tpr',
'cobrotoxin.tpr',
'cobrotoxin_2024_4.tpr',
'trzfile.trz',
'__init__.py',
'adk_oplsaa_rama.npy',
'adk_oplsaa_LYS_janin.npy',
'adk_oplsaa_janin.npy',
'adk_oplsaa_GLY_rama.npy',
'adk_oplsaa_dihedral.npy',
'adk_oplsaa_dihedral_list.npy',
'adk_oplsaa_CA_rmsf.npy',
'mol2_comments_header_bat.npy',
'legacy_DCD_NAMD_coords.npy',
'legacy_DCD_c36_coords.npy',
'legacy_DCD_adk_coords.npy',
'2r9r-1b.psf',
'SiN_tric_namd.psf',
'adk.psf',
'adk_closed_NAMD.psf',
'adk_notop.psf',
'adk_notop_BAD.psf',
'namd_cgenff.psf',
'tip125_tric_C36.psf',
'parmed_ala3.psf',
'nosegid.psf',
'trz_psf.psf',
'watdyn.psf',
'1a2c_ins_code.psf',
'adk_oplsaa.gro',
'empty_atom.gro',
'dppc_vesicle_hg.gro',
'huge_box.gro',
'grovels.gro',
'missing_atomname.gro',
'martini_dppc_chol_bilayer.gro',
'make_whole.gro',
'sample_velocity_file.gro',
'sameresid_diffresname.gro',
'residwrap.gro',
'residwrap_0base.gro',
'plength.gro',
'two_water_gro_widebox.gro',
'two_water_gro_nonames.gro',
'two_water_gro_multiframe.gro',
'two_water_gro.gro',
'adk_oplsaa.xtc',
'aux_edr.xtc',
'cobrotoxin.xtc',
'xyz_random_walk.xtc',
'xtc_test_only_10_frame_10_atoms.xtc',
'SiN_tric_namd.dcd',
'adk_dims.dcd',
'adk_dims2.dcd',
'adk_gbis_tmd-fast1_NAMD.dcd',
'empty.dcd',
'tip125_tric_C36.dcd',
'watdyn.dcd',
]

py3.install_sources(
  python_sources,
  subdir: 'MDAnalysisTests/data'
)

subdir('analysis')
subdir('mol2')
subdir('contacts')
subdir('Amber')
subdir('gms')
subdir('lammps')
subdir('coordinates')
subdir('dlpoly')
subdir('gromos11')
subdir('dssp')
subdir('tprs')
subdir('capping')
subdir('merge')
subdir('gromacs')
subdir('windows')
