python_sources = [
'test.xyz.bz2',
'test.xyz',
'test.xtc',
'test.txyz',
'test.trr',
'test_topology.pdb',
'test.tng',
'test_incomplete_vel.gro',
'test.h5md',
'test.gro.bz2',
'test.gro',
'test.dcd',
'test.arc',
'README.md',
'new_hexane.arc',
'__init__.py',
'create_h5md_data.py',
'create_data.py',
]

py3.install_sources(
  python_sources,
  subdir: 'MDAnalysisTests/data/coordinates'
)
