# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in with Sphinx
sphinx:
  configuration: package/doc/sphinx/source/conf.py

# Set the version of Python and other tools you might need
build:
  os: ubuntu-lts-latest
  tools:
    python: "miniforge3-latest"

# Optionally set the version of Python and requirements required to build your docs
python:
  install:
    - method: pip
      path: package

conda:
  environment: maintainer/conda/environment.yml
