#-*- coding:utf-8 -*-

# This file is generated from the AUTHORS file during the installation process.
# Do not edit it as your changes will be overwritten.

__authors__ = [
    u"Naveen Michaud-Agrawal",
    u"Elizabeth J. Denning",
    u"Christian Beckstein (logo)",
    u"Joshua L. Adelman",
    u"Henok Ademtew",
    u"Shobhit Agarwal",
    u"Aya M. Alaa",
    u"Irfan Alibay",
    u"Kazi Shudipto Amin",
    u"Anshul Angaria",
    u"Luís Pedro Borges Araújo",
    u"Balasubramanian",
    u"Utkarsh Bansal",
    u"Patricio Barletta",
    u"Leonardo Barneschi",
    u"Jonathan Barnoud",
    u"Estefania Barreto-Ojeda",
    u"Tone Bengtsen",
    u"Alejandro Bernardin",
    u"Ninad Bhat",
    u"Mateusz Bieniek",
    u"Kavya Bisht",
    u"Wouter Boomsma",
    u"Jose Borreguero",
    u"Cédric Bouysset",
    u"Kevin Boyd",
    u"Meet Brijwani",
    u"Bart Bruininks",
    u"Sébastien Buchoux",
    u"Sören von Bülow",
    u"Yantong Cai",
    u"David Caplan",
    u"Yuanyu Chang",
    u"Pratham Chauhan",
    u"Matthieu Chavent",
    u"Haochuan Chen",
    u"Xu Hong Chen",
    u"Kathleen Clark",
    u"Jennifer A Clark",
    u"Orion Cohen",
    u"Charlie Cook",
    u"Ruggero Cortini",
    u"Nicholas Craven",
    u"Ramon Crehuet",
    u"Davide Cruz",
    u"Matthew Davies",
    u"Robert Delgado",
    u"John Detlefs",
    u"Xavier Deupi",
    u"Bradley Dice",
    u"Jan Domanski",
    u"David L. Dotson",
    u"Mark D. Driver",
    u"Ali Ehlen",
    u"Daniel J. Evans",
    u"Shujie Fan",
    u"Bjarne Feddersen",
    u"Lennard van der Feltz",
    u"Jake Fennick",
    u"Philip Fowler",
    u"Guillaume Fraux",
    u"Anirvinya G",
    u"Michael Gecht",
    u"Ahmed Salah Ghoneim",
    u"Mikhail Glagolev",
    u"William Glass",
    u"Jenna M. Swarthout Goddard",
    u"Joseph Goose",
    u"Alexander Gorfer",
    u"Richard J. Gowers",
    u"Lukas Grossar",
    u"Abhinav Gupta",
    u"Akshay Gupta",
    u"Pratik Gupta",
    u"Sumit Gupta",
    u"Benjamin Hall",
    u"Ameya Harmalkar",
    u"Ivan Hristov",
    u"Eugen Hruska",
    u"Kyle J. Huston",
    u"Siddharth Jain",
    u"Edis Jakupovic",
    u"Joe Jordan",
    u"Henrik Jäger",
    u"Uma D Kadam",
    u"Aditya Kamath",
    u"Jon Kapla",
    u"Ian M. Kenney",
    u"Aditya Keshari",
    u"Haleema Khan",
    u"Navya Khare",
    u"Utsav Khatu",
    u"Andrew William King",
    u"Henry Kobin",
    u"Abhishek A. Kognole",
    u"Kosuke Kudo",
    u"Atharva Kulkarni",
    u"Manish Kumar",
    u"Mohit Kumar",
    u"Shubham Kumar",
    u"Alia Lescoulie",
    u"Zhenbo Li",
    u"Max Linke",
    u"Philip Loche",
    u"Jinju Lu",
    u"Hugo MacDermott-Opeskin",
    u"Shaivi Malik",
    u"Egor Marin",
    u"Domenico Marson",
    u"Micaela Matta",
    u"Andrew R. McCluskey",
    u"Robert McGibbon",
    u"Kurt McKee",
    u"Rocco Meli",
    u"Manuel Nuno Melo",
    u"Marcelo C. R. Melo",
    u"Dominik 'Rathann' Mierzejewski",
    u"David Minh",
    u"Geongi Moon",
    u"Sampurna Mukherjee",
    u"Henry Mull",
    u"Morgan L. Nance",
    u"Fiona B. Naughton",
    u"Alex Nesterenko",
    u"Hai Nguyen",
    u"Sang Young Noh",
    u"Meghan Osato",
    u"Daniele Padula",
    u"Nabarun Pal",
    u"Mattia F. Palermo",
    u"Dimitrios Papageorgiou",
    u"Rafael R. Pappalardo",
    u"Vishal Parmar",
    u"Danny Parton",
    u"Shakul Pathak",
    u"Christian Pfaendner",
    u"Joshua L. Phillips",
    u"Marcelo D. Poleto",
    u"Hannah Pollak",
    u"Kashish Punjani",
    u"Michael Quevillon",
    u"Vedant Rathore",
    u"Tyler Reddy",
    u"Pedro Reis",
    u"Paul Rigor",
    u"Andrea Rizzi",
    u"Xiaoxu Ruan",
    u"Carlos Yanez S.",
    u"Utkarsh Saxena",
    u"Moritz Schaeffler",
    u"Alexander Schlaich",
    u"Marcello Sega",
    u"Ricky Sexton",
    u"Sean L. Seyler",
    u"Faraaz Shah",
    u"Sulay Shah",
    u"Abhishek Shandilya",
    u"Shubham Sharma",
    u"Laksh Krishna Sharma",
    u"Rishabh Shukla",
    u"Karthikeyan Singaravelan",
    u"Tamandeep Singh",
    u"Brigitta Sipőcz",
    u"Paul Smith",
    u"Andy Somogyi",
    u"Caio S. Souza",
    u"Kai Niklas Spauszus",
    u"David van der Spoel",
    u"Shantanu Srivastava",
    u"Lukas Stelzl",
    u"Jan Stevens",
    u"Gorman Stock",
    u"Philipp Stärk",
    u"Johannes Stöckelmaier",
    u"Fenil Suchak",
    u"Ayush Suhane",
    u"Filip T. Szczypiński",
    u"Sukeerti T",
    u"Matthijs Tadema",
    u"Valerij Talagayev",
    u"Joao Miguel Correia Teixeira",
    u"Paarth Thadani",
    u"Matthew W. Thompson",
    u"Hao Tian",
    u"Matteo Tiberti",
    u"Zaheer Timol",
    u"Wiep van der Toorn",
    u"Mieczyslaw Torchala",
    u"Aditi Tripathi",
    u"Joshua Raphael Uy",
    u"Heet Vekariya",
    u"Mark Verma",
    u"Josh Vermaas",
    u"Isaac Virshup",
    u"Lily Wang",
    u"Leon Wehrhan",
    u"Nestor Wendt",
    u"Lawson Woods",
    u"Zhiyi Wu",
    u"Tengyu Xie",
    u"Zhuyi Xue",
    u"Mingyi Xue",
    u"Alexander Yang",
    u"Tanish Yelgoe",
    u"Juan Eiros Zamora",
    u"Johannes Zeman",
    u"Yibo Zhang",
    u"Raymond Zhao",
    u"Jia-Xin Zhu",
    u"Yuxuan Zhuang",
    u"Fabian Zills",
    u"Oliver Beckstein"
]
