python_sources = [
  'due.py',
  'exceptions.py',
  '__init__.py',
  'units.py',
  'version.py',
]

py3.install_sources(
  python_sources,
  subdir: 'MDAnalysis'
)

subdir('auxiliary')
subdir('guesser')
subdir('selections')
subdir('transformations')
subdir('visualization')
subdir('tests')
subdir('lib')
subdir('analysis')
subdir('converters')
subdir('coordinates')
subdir('core')
subdir('topology')
