python_sources = [
'dummy.top',
'dummy.mdp',
'dummy.gro',
'dummy_5.1.tpr',
'dummy_3.3.4.tpr',
'dummy_3.3.4.top',
'dummy_2023.tpr',
'dummy_2022-rc1.tpr',
'dummy_2021.tpr',
'dummy_2021_double.tpr',
'dummy_2020.tpr',
'dummy_2020_double.tpr',
'dummy_2020-beta2.tpr',
'dummy_2019-beta3.tpr',
'dummy_2018.tpr',
'dummy_2018.mdp',
'dummy_2016.tpr',
'__init__.py',
'dummy_2024.tpr',
'dummy_2024_4.tpr',
'dummy_2025_0.tpr',
]

py3.install_sources(
  python_sources,
  subdir: 'MDAnalysisTests/data/tprs/all_bonded'
)

