python_sources = [
'extra-interactions-4.0.7.tpr',
'extra-interactions-2023.tpr',
'extra-interactions-2022-rc1.tpr',
'extra-interactions-2021.tpr',
'extra-interactions-2020.tpr',
'extra-interactions-2018.tpr',
'extra-interactions-2016.3.tpr',
'dummy.top',
'dummy.gro',
'dummy_4.0.7.top',
'dummy_4.0.7.mdp',
'dummy_2021.top',
'dummy_2021.gro',
'dummy_2020.mdp',
'dummy_2018.mdp',
'__init__.py',
'extra-interactions-2024.tpr',
'extra-interactions-2024_4.tpr',
'extra-interactions-2025_0.tpr',
]

py3.install_sources(
  python_sources,
  subdir: 'MDAnalysisTests/data/tprs/virtual_sites'
)

