
name: mdanalysis
channels:
  - biobuilds
  - conda-forge
  - defaults
dependencies:
  - biopython
  - codecov
  - cython
  - griddataformats
  - gsd==1.9.3
  - hypothesis
  - matplotlib
  - mmtf-python
  - mock
  - networkx
  - numpy>=1.17.3
  - psutil
  - pytest
  - pytest-cov
  - pytest-xdist
  - scipy
  - sphinx==1.8.5
  - tidynamics>=1.0.0
  - tqdm>=4.43.0
  - pip:
      - duecredit
      - msmb_theme==1.2.0
      - parmed
      - sphinx_rtd_theme
      - sphinx-sitemap
