/* Generated by Pyrex 0.9.4.1 on Tue Jun 12 23:01:00 2007 */

#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
__PYX_EXTERN_C double pow(double, double);
#include "Numeric/arrayobject.h"
#include "readdcd.h"
#include "correl.h"


typedef struct {PyObject **p; char *s;} __Pyx_InternTabEntry; /*proto*/
typedef struct {PyObject **p; char *s; long n;} __Pyx_StringTabEntry; /*proto*/
static PyObject *__Pyx_UnpackItem(PyObject *, int); /*proto*/
static int __Pyx_EndUnpack(PyObject *, int); /*proto*/
static int __Pyx_PrintItem(PyObject *); /*proto*/
static int __Pyx_PrintNewline(void); /*proto*/
static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb); /*proto*/
static void __Pyx_ReRaise(void); /*proto*/
static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list); /*proto*/
static PyObject *__Pyx_GetExcValue(void); /*proto*/
static int __Pyx_ArgTypeTest(PyObject *obj, PyTypeObject *type, int none_allowed, char *name); /*proto*/
static int __Pyx_TypeTest(PyObject *obj, PyTypeObject *type); /*proto*/
static int __Pyx_GetStarArgs(PyObject **args, PyObject **kwds, char *kwd_list[], int nargs, PyObject **args2, PyObject **kwds2); /*proto*/
static void __Pyx_WriteUnraisable(char *name); /*proto*/
static void __Pyx_AddTraceback(char *funcname); /*proto*/
static PyTypeObject *__Pyx_ImportType(char *module_name, char *class_name, long size);  /*proto*/
static int __Pyx_SetVtable(PyObject *dict, void *vtable); /*proto*/
static int __Pyx_GetVtable(PyObject *dict, void *vtabptr); /*proto*/
static PyObject *__Pyx_CreateClass(PyObject *bases, PyObject *dict, PyObject *name, char *modname); /*proto*/
static int __Pyx_InternStrings(__Pyx_InternTabEntry *t); /*proto*/
static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/
static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name); /*proto*/

static PyObject *__pyx_m;
static PyObject *__pyx_b;
static int __pyx_lineno;
static char *__pyx_filename;
static char **__pyx_f;

/* Declarations from _dcdtest */

typedef struct {
  fio_fd fd;
  fio_size_t header_size;
  int natoms;
  int nsets;
  int setsread;
  int istart;
  int nsavc;
  double delta;
  int nfixed;
  int (*freeind);
  float (*fixedcoords);
  int reverse;
  int charmm;
  int first;
  int with_unitcell;
} __pyx_t_8_dcdtest_dcdhandle;

static PyTypeObject *__pyx_ptype_8_dcdtest_ArrayType = 0;
static int (__pyx_f_8_dcdtest_jump_to_frame(__pyx_t_8_dcdtest_dcdhandle (*),int )); /*proto*/

/* Implementation of _dcdtest */


static PyObject *__pyx_n_Numeric;
static PyObject *__pyx_n___read_timecorrel;
static PyObject *__pyx_n___read_timeseries;

static PyObject *__pyx_n__dcd_C_ptr;
static PyObject *__pyx_n_len;
static PyObject *__pyx_n_Exception;
static PyObject *__pyx_n_array;
static PyObject *__pyx_n_Int32;
static PyObject *__pyx_n_Float64;
static PyObject *__pyx_n_zeros;
static PyObject *__pyx_n_Float32;
static PyObject *__pyx_n_IOError;

static PyObject *__pyx_k2p;
static PyObject *__pyx_k3p;
static PyObject *__pyx_k4p;
static PyObject *__pyx_k5p;

static char (__pyx_k2[]) = "No data requested, timeseries is empty";
static char (__pyx_k3[]) = "Error jumping to starting frame";
static char (__pyx_k4[]) = "Error skipping frame from DCD file";
static char (__pyx_k5[]) = "Error reading frame from DCD file";

static PyObject *__pyx_f_8_dcdtest___read_timecorrel(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_8_dcdtest___read_timecorrel(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_self = 0;
  PyObject *__pyx_v_atoms = 0;
  PyObject *__pyx_v_atomcounts = 0;
  PyObject *__pyx_v_format = 0;
  PyObject *__pyx_v_auxdata = 0;
  int __pyx_v_sizedata;
  int __pyx_v_lowerb;
  int __pyx_v_upperb;
  int __pyx_v_start;
  int __pyx_v_stop;
  int __pyx_v_skip;
  __pyx_t_8_dcdtest_dcdhandle (*__pyx_v_dcd);
  PyArrayObject *__pyx_v_atomlist;
  PyArrayObject *__pyx_v_atomcountslist;
  PyArrayObject *__pyx_v_auxlist;
  PyArrayObject *__pyx_v_data;
  PyArrayObject *__pyx_v_temp;
  float (*__pyx_v_tempX);
  float (*__pyx_v_tempY);
  float (*__pyx_v_tempZ);
  int __pyx_v_rc;
  char (*__pyx_v_fmtstr);
  int __pyx_v_numframes;
  int __pyx_v_numdata;
  int __pyx_v_range;
  int __pyx_v_index;
  int __pyx_v_numskip;
  int __pyx_v_i;
  int __pyx_v_j;
  float (__pyx_v_unitcell[6]);
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  int __pyx_2;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  static char *__pyx_argnames[] = {"self","atoms","atomcounts","format","auxdata","sizedata","lowerb","upperb","start","stop","skip",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OOOOOiiiiii", __pyx_argnames, &__pyx_v_self, &__pyx_v_atoms, &__pyx_v_atomcounts, &__pyx_v_format, &__pyx_v_auxdata, &__pyx_v_sizedata, &__pyx_v_lowerb, &__pyx_v_upperb, &__pyx_v_start, &__pyx_v_stop, &__pyx_v_skip)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_atoms);
  Py_INCREF(__pyx_v_atomcounts);
  Py_INCREF(__pyx_v_format);
  Py_INCREF(__pyx_v_auxdata);
  __pyx_v_atomlist = ((PyArrayObject *)Py_None); Py_INCREF(Py_None);
  __pyx_v_atomcountslist = ((PyArrayObject *)Py_None); Py_INCREF(Py_None);
  __pyx_v_auxlist = ((PyArrayObject *)Py_None); Py_INCREF(Py_None);
  __pyx_v_data = ((PyArrayObject *)Py_None); Py_INCREF(Py_None);
  __pyx_v_temp = ((PyArrayObject *)Py_None); Py_INCREF(Py_None);

  /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":66 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_self, __pyx_n__dcd_C_ptr); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 66; goto __pyx_L1;}
  __pyx_v_dcd = ((__pyx_t_8_dcdtest_dcdhandle (*))PyCObject_AsVoidPtr(__pyx_1));
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":68 */
  __pyx_2 = (__pyx_v_stop == (-1));
  if (__pyx_2) {
    __pyx_v_stop = __pyx_v_dcd->nsets;
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":69 */
  __pyx_v_numframes = (((__pyx_v_stop - __pyx_v_start) + 1) / __pyx_v_skip);

  /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":71 */
  __pyx_1 = __Pyx_GetName(__pyx_b, __pyx_n_len); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 71; goto __pyx_L1;}
  __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 71; goto __pyx_L1;}
  Py_INCREF(__pyx_v_format);
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_v_format);
  __pyx_4 = PyObject_CallObject(__pyx_1, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 71; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_2 = PyInt_AsLong(__pyx_4); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 71; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  __pyx_v_numdata = __pyx_2;

  /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":72 */
  __pyx_2 = (__pyx_v_numdata == 0);
  if (__pyx_2) {

    /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":73 */
    __pyx_1 = __Pyx_GetName(__pyx_b, __pyx_n_Exception); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 73; goto __pyx_L1;}
    __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 73; goto __pyx_L1;}
    Py_INCREF(__pyx_k2p);
    PyTuple_SET_ITEM(__pyx_3, 0, __pyx_k2p);
    __pyx_4 = PyObject_CallObject(__pyx_1, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 73; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __Pyx_Raise(__pyx_4, 0, 0);
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 73; goto __pyx_L1;}
    goto __pyx_L3;
  }
  __pyx_L3:;

  /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":74 */
  __pyx_v_fmtstr = PyString_AsString(__pyx_v_format);

  /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":75 */
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_Numeric); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 75; goto __pyx_L1;}
  __pyx_3 = PyObject_GetAttr(__pyx_1, __pyx_n_array); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 75; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_4 = __Pyx_GetName(__pyx_m, __pyx_n_Numeric); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 75; goto __pyx_L1;}
  __pyx_1 = PyObject_GetAttr(__pyx_4, __pyx_n_Int32); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 75; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  __pyx_4 = PyTuple_New(2); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 75; goto __pyx_L1;}
  Py_INCREF(__pyx_v_atoms);
  PyTuple_SET_ITEM(__pyx_4, 0, __pyx_v_atoms);
  PyTuple_SET_ITEM(__pyx_4, 1, __pyx_1);
  __pyx_1 = 0;
  __pyx_1 = PyObject_CallObject(__pyx_3, __pyx_4); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 75; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  if (!__Pyx_TypeTest(__pyx_1, __pyx_ptype_8_dcdtest_ArrayType)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 75; goto __pyx_L1;}
  Py_DECREF(((PyObject *)__pyx_v_atomlist));
  __pyx_v_atomlist = ((PyArrayObject *)__pyx_1);
  __pyx_1 = 0;

  /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":76 */
  __pyx_3 = __Pyx_GetName(__pyx_m, __pyx_n_Numeric); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 76; goto __pyx_L1;}
  __pyx_4 = PyObject_GetAttr(__pyx_3, __pyx_n_array); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 76; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_Numeric); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 76; goto __pyx_L1;}
  __pyx_3 = PyObject_GetAttr(__pyx_1, __pyx_n_Int32); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 76; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyTuple_New(2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 76; goto __pyx_L1;}
  Py_INCREF(__pyx_v_atomcounts);
  PyTuple_SET_ITEM(__pyx_1, 0, __pyx_v_atomcounts);
  PyTuple_SET_ITEM(__pyx_1, 1, __pyx_3);
  __pyx_3 = 0;
  __pyx_3 = PyObject_CallObject(__pyx_4, __pyx_1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 76; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  if (!__Pyx_TypeTest(__pyx_3, __pyx_ptype_8_dcdtest_ArrayType)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 76; goto __pyx_L1;}
  Py_DECREF(((PyObject *)__pyx_v_atomcountslist));
  __pyx_v_atomcountslist = ((PyArrayObject *)__pyx_3);
  __pyx_3 = 0;

  /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":77 */
  __pyx_4 = __Pyx_GetName(__pyx_m, __pyx_n_Numeric); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 77; goto __pyx_L1;}
  __pyx_1 = PyObject_GetAttr(__pyx_4, __pyx_n_array); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 77; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  __pyx_3 = __Pyx_GetName(__pyx_m, __pyx_n_Numeric); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 77; goto __pyx_L1;}
  __pyx_4 = PyObject_GetAttr(__pyx_3, __pyx_n_Float64); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 77; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_3 = PyTuple_New(2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 77; goto __pyx_L1;}
  Py_INCREF(__pyx_v_auxdata);
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_v_auxdata);
  PyTuple_SET_ITEM(__pyx_3, 1, __pyx_4);
  __pyx_4 = 0;
  __pyx_4 = PyObject_CallObject(__pyx_1, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 77; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  if (!__Pyx_TypeTest(__pyx_4, __pyx_ptype_8_dcdtest_ArrayType)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 77; goto __pyx_L1;}
  Py_DECREF(((PyObject *)__pyx_v_auxlist));
  __pyx_v_auxlist = ((PyArrayObject *)__pyx_4);
  __pyx_4 = 0;

  /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":82 */
  __pyx_v_range = ((__pyx_v_upperb - __pyx_v_lowerb) + 1);

  /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":85 */
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_Numeric); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 85; goto __pyx_L1;}
  __pyx_3 = PyObject_GetAttr(__pyx_1, __pyx_n_zeros); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 85; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_4 = PyInt_FromLong(__pyx_v_sizedata); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 85; goto __pyx_L1;}
  __pyx_1 = PyInt_FromLong(__pyx_v_numframes); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 85; goto __pyx_L1;}
  __pyx_5 = PyTuple_New(2); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 85; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_5, 0, __pyx_4);
  PyTuple_SET_ITEM(__pyx_5, 1, __pyx_1);
  __pyx_4 = 0;
  __pyx_1 = 0;
  __pyx_4 = __Pyx_GetName(__pyx_m, __pyx_n_Numeric); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 85; goto __pyx_L1;}
  __pyx_1 = PyObject_GetAttr(__pyx_4, __pyx_n_Float64); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 85; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  __pyx_4 = PyTuple_New(2); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 85; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_4, 0, __pyx_5);
  PyTuple_SET_ITEM(__pyx_4, 1, __pyx_1);
  __pyx_5 = 0;
  __pyx_1 = 0;
  __pyx_5 = PyObject_CallObject(__pyx_3, __pyx_4); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 85; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  if (!__Pyx_TypeTest(__pyx_5, __pyx_ptype_8_dcdtest_ArrayType)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 85; goto __pyx_L1;}
  Py_DECREF(((PyObject *)__pyx_v_data));
  __pyx_v_data = ((PyArrayObject *)__pyx_5);
  __pyx_5 = 0;

  /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":86 */
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_Numeric); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 86; goto __pyx_L1;}
  __pyx_3 = PyObject_GetAttr(__pyx_1, __pyx_n_zeros); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 86; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_4 = PyInt_FromLong(3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 86; goto __pyx_L1;}
  __pyx_5 = PyInt_FromLong(__pyx_v_range); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 86; goto __pyx_L1;}
  __pyx_1 = PyTuple_New(2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 86; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_1, 0, __pyx_4);
  PyTuple_SET_ITEM(__pyx_1, 1, __pyx_5);
  __pyx_4 = 0;
  __pyx_5 = 0;
  __pyx_4 = __Pyx_GetName(__pyx_m, __pyx_n_Numeric); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 86; goto __pyx_L1;}
  __pyx_5 = PyObject_GetAttr(__pyx_4, __pyx_n_Float32); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 86; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  __pyx_4 = PyTuple_New(2); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 86; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_4, 0, __pyx_1);
  PyTuple_SET_ITEM(__pyx_4, 1, __pyx_5);
  __pyx_1 = 0;
  __pyx_5 = 0;
  __pyx_1 = PyObject_CallObject(__pyx_3, __pyx_4); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 86; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  if (!__Pyx_TypeTest(__pyx_1, __pyx_ptype_8_dcdtest_ArrayType)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 86; goto __pyx_L1;}
  Py_DECREF(((PyObject *)__pyx_v_temp));
  __pyx_v_temp = ((PyArrayObject *)__pyx_1);
  __pyx_1 = 0;

  /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":87 */
  __pyx_v_tempX = ((float (*))(__pyx_v_temp->data + (0 * (__pyx_v_temp->strides[0]))));

  /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":88 */
  __pyx_v_tempY = ((float (*))(__pyx_v_temp->data + (1 * (__pyx_v_temp->strides[0]))));

  /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":89 */
  __pyx_v_tempZ = ((float (*))(__pyx_v_temp->data + (2 * (__pyx_v_temp->strides[0]))));

  /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":92 */
  __pyx_v_rc = fio_fseek(__pyx_v_dcd->fd,__pyx_v_dcd->header_size,0);

  /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":93 */
  __pyx_v_dcd->setsread = 0;

  /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":94 */
  __pyx_v_dcd->first = 1;

  /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":97 */
  __pyx_2 = (__pyx_v_start > 0);
  if (__pyx_2) {

    /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":98 */
    __pyx_v_rc = jump_to_dcdstep(__pyx_v_dcd->fd,__pyx_v_dcd->natoms,__pyx_v_dcd->nsets,__pyx_v_dcd->nfixed,__pyx_v_dcd->charmm,__pyx_v_dcd->header_size,__pyx_v_start);

    /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":99 */
    __pyx_2 = (__pyx_v_rc < 0);
    if (__pyx_2) {

      /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":100 */
      __pyx_5 = __Pyx_GetName(__pyx_b, __pyx_n_IOError); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 100; goto __pyx_L1;}
      __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 100; goto __pyx_L1;}
      Py_INCREF(__pyx_k3p);
      PyTuple_SET_ITEM(__pyx_3, 0, __pyx_k3p);
      __pyx_4 = PyObject_CallObject(__pyx_5, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 100; goto __pyx_L1;}
      Py_DECREF(__pyx_5); __pyx_5 = 0;
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      __Pyx_Raise(__pyx_4, 0, 0);
      Py_DECREF(__pyx_4); __pyx_4 = 0;
      {__pyx_filename = __pyx_f[0]; __pyx_lineno = 100; goto __pyx_L1;}
      goto __pyx_L5;
    }
    __pyx_L5:;

    /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":101 */
    __pyx_v_dcd->first = 0;

    /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":102 */
    __pyx_v_dcd->setsread = __pyx_v_start;
    goto __pyx_L4;
  }
  __pyx_L4:;

  /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":107 */
  for (__pyx_v_i = 0; __pyx_v_i < __pyx_v_numframes; ++__pyx_v_i) {

    /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":108 */
    __pyx_2 = (__pyx_v_skip > 1);
    if (__pyx_2) {

      /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":111 */
      __pyx_v_numskip = ((__pyx_v_skip - (__pyx_v_dcd->setsread % __pyx_v_skip)) - 1);

      /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":112 */
      __pyx_v_rc = skip_dcdstep(__pyx_v_dcd->fd,__pyx_v_dcd->natoms,__pyx_v_dcd->nfixed,__pyx_v_dcd->charmm,__pyx_v_numskip);

      /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":113 */
      __pyx_2 = (__pyx_v_rc < 0);
      if (__pyx_2) {

        /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":114 */
        __pyx_1 = __Pyx_GetName(__pyx_b, __pyx_n_IOError); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 114; goto __pyx_L1;}
        __pyx_5 = PyTuple_New(1); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 114; goto __pyx_L1;}
        Py_INCREF(__pyx_k4p);
        PyTuple_SET_ITEM(__pyx_5, 0, __pyx_k4p);
        __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_5); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 114; goto __pyx_L1;}
        Py_DECREF(__pyx_1); __pyx_1 = 0;
        Py_DECREF(__pyx_5); __pyx_5 = 0;
        __Pyx_Raise(__pyx_3, 0, 0);
        Py_DECREF(__pyx_3); __pyx_3 = 0;
        {__pyx_filename = __pyx_f[0]; __pyx_lineno = 114; goto __pyx_L1;}
        goto __pyx_L9;
      }
      __pyx_L9:;

      /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":115 */
      __pyx_v_dcd->setsread = (__pyx_v_dcd->setsread + __pyx_v_numskip);
      goto __pyx_L8;
    }
    __pyx_L8:;

    /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":116 */
    __pyx_v_rc = read_dcdsubset(__pyx_v_dcd->fd,__pyx_v_dcd->natoms,__pyx_v_lowerb,__pyx_v_upperb,__pyx_v_tempX,__pyx_v_tempY,__pyx_v_tempZ,__pyx_v_unitcell,__pyx_v_dcd->nfixed,__pyx_v_dcd->first,__pyx_v_dcd->freeind,__pyx_v_dcd->fixedcoords,__pyx_v_dcd->reverse,__pyx_v_dcd->charmm);

    /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":117 */
    __pyx_v_dcd->first = 0;

    /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":118 */
    __pyx_v_dcd->setsread = (__pyx_v_dcd->setsread + 1);

    /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":119 */
    __pyx_2 = (__pyx_v_rc < 0);
    if (__pyx_2) {

      /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":120 */
      __pyx_4 = __Pyx_GetName(__pyx_b, __pyx_n_IOError); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 120; goto __pyx_L1;}
      __pyx_1 = PyTuple_New(1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 120; goto __pyx_L1;}
      Py_INCREF(__pyx_k5p);
      PyTuple_SET_ITEM(__pyx_1, 0, __pyx_k5p);
      __pyx_5 = PyObject_CallObject(__pyx_4, __pyx_1); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 120; goto __pyx_L1;}
      Py_DECREF(__pyx_4); __pyx_4 = 0;
      Py_DECREF(__pyx_1); __pyx_1 = 0;
      __Pyx_Raise(__pyx_5, 0, 0);
      Py_DECREF(__pyx_5); __pyx_5 = 0;
      {__pyx_filename = __pyx_f[0]; __pyx_lineno = 120; goto __pyx_L1;}
      goto __pyx_L10;
    }
    __pyx_L10:;

    /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":122 */
    copyseries(__pyx_v_i,__pyx_v_data->data,__pyx_v_data->strides,__pyx_v_tempX,__pyx_v_tempY,__pyx_v_tempZ,__pyx_v_fmtstr,__pyx_v_numdata,((int (*))__pyx_v_atomlist->data),((int (*))__pyx_v_atomcountslist->data),__pyx_v_lowerb,((double (*))__pyx_v_auxlist->data));

    /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":123 */
    PyErr_CheckSignals();
    __pyx_L6:;
  }
  __pyx_L7:;

  /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":126 */
  __pyx_v_rc = fio_fseek(__pyx_v_dcd->fd,__pyx_v_dcd->header_size,0);

  /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":127 */
  __pyx_v_dcd->setsread = 0;

  /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":128 */
  __pyx_v_dcd->first = 1;

  /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":129 */
  Py_INCREF(((PyObject *)__pyx_v_data));
  __pyx_r = ((PyObject *)__pyx_v_data);
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  __Pyx_AddTraceback("_dcdtest.__read_timecorrel");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_atomlist);
  Py_DECREF(__pyx_v_atomcountslist);
  Py_DECREF(__pyx_v_auxlist);
  Py_DECREF(__pyx_v_data);
  Py_DECREF(__pyx_v_temp);
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_atoms);
  Py_DECREF(__pyx_v_atomcounts);
  Py_DECREF(__pyx_v_format);
  Py_DECREF(__pyx_v_auxdata);
  return __pyx_r;
}

static PyObject *__pyx_k6p;
static PyObject *__pyx_k7p;
static PyObject *__pyx_k8p;

static char (__pyx_k6[]) = "No atoms passed into __read_timeseries function";
static char (__pyx_k7[]) = "Error skipping frame from DCD file";
static char (__pyx_k8[]) = "Error reading frame from DCD file";

static PyObject *__pyx_f_8_dcdtest___read_timeseries(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_8_dcdtest___read_timeseries(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_self = 0;
  PyObject *__pyx_v_atoms = 0;
  int __pyx_v_skip;
  __pyx_t_8_dcdtest_dcdhandle (*__pyx_v_dcd);
  PyArrayObject *__pyx_v_atomlist;
  PyArrayObject *__pyx_v_coord;
  PyArrayObject *__pyx_v_temp;
  float (*__pyx_v_tempX);
  float (*__pyx_v_tempY);
  float (*__pyx_v_tempZ);
  int __pyx_v_rc;
  int __pyx_v_numframes;
  int __pyx_v_numatoms;
  int __pyx_v_lowerb;
  int __pyx_v_upperb;
  int __pyx_v_range;
  int __pyx_v_index;
  int __pyx_v_numskip;
  int __pyx_v_i;
  int __pyx_v_j;
  float (__pyx_v_unitcell[6]);
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  int __pyx_4;
  PyObject *__pyx_5 = 0;
  PyObject *__pyx_6 = 0;
  static char *__pyx_argnames[] = {"self","atoms","skip",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OOi", __pyx_argnames, &__pyx_v_self, &__pyx_v_atoms, &__pyx_v_skip)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_atoms);
  __pyx_v_atomlist = ((PyArrayObject *)Py_None); Py_INCREF(Py_None);
  __pyx_v_coord = ((PyArrayObject *)Py_None); Py_INCREF(Py_None);
  __pyx_v_temp = ((PyArrayObject *)Py_None); Py_INCREF(Py_None);

  /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":138 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_self, __pyx_n__dcd_C_ptr); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 138; goto __pyx_L1;}
  __pyx_v_dcd = ((__pyx_t_8_dcdtest_dcdhandle (*))PyCObject_AsVoidPtr(__pyx_1));
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":140 */
  __pyx_v_numframes = (__pyx_v_dcd->nsets / __pyx_v_skip);

  /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":142 */
  __pyx_1 = __Pyx_GetName(__pyx_b, __pyx_n_len); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 142; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 142; goto __pyx_L1;}
  Py_INCREF(__pyx_v_atoms);
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_v_atoms);
  __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 142; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_4 = PyInt_AsLong(__pyx_3); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 142; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_v_numatoms = __pyx_4;

  /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":143 */
  __pyx_4 = (__pyx_v_numatoms == 0);
  if (__pyx_4) {

    /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":144 */
    __pyx_1 = __Pyx_GetName(__pyx_b, __pyx_n_Exception); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 144; goto __pyx_L1;}
    __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 144; goto __pyx_L1;}
    Py_INCREF(__pyx_k6p);
    PyTuple_SET_ITEM(__pyx_2, 0, __pyx_k6p);
    __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 144; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __Pyx_Raise(__pyx_3, 0, 0);
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 144; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":145 */
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_Numeric); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 145; goto __pyx_L1;}
  __pyx_2 = PyObject_GetAttr(__pyx_1, __pyx_n_array); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 145; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 145; goto __pyx_L1;}
  Py_INCREF(__pyx_v_atoms);
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_v_atoms);
  __pyx_1 = PyObject_CallObject(__pyx_2, __pyx_3); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 145; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  if (!__Pyx_TypeTest(__pyx_1, __pyx_ptype_8_dcdtest_ArrayType)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 145; goto __pyx_L1;}
  Py_DECREF(((PyObject *)__pyx_v_atomlist));
  __pyx_v_atomlist = ((PyArrayObject *)__pyx_1);
  __pyx_1 = 0;

  /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":147 */
  __pyx_2 = PyInt_FromLong(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 147; goto __pyx_L1;}
  __pyx_3 = PyObject_GetItem(__pyx_v_atoms, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 147; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_4 = PyInt_AsLong(__pyx_3); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 147; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_v_lowerb = __pyx_4;

  /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":148 */
  __pyx_1 = PyInt_FromLong((-1)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 148; goto __pyx_L1;}
  __pyx_2 = PyObject_GetItem(__pyx_v_atoms, __pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 148; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_4 = PyInt_AsLong(__pyx_2); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 148; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_v_upperb = __pyx_4;

  /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":149 */
  __pyx_v_range = ((__pyx_v_upperb - __pyx_v_lowerb) + 1);

  /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":151 */
  __pyx_3 = __Pyx_GetName(__pyx_m, __pyx_n_Numeric); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 151; goto __pyx_L1;}
  __pyx_1 = PyObject_GetAttr(__pyx_3, __pyx_n_zeros); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 151; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_2 = PyInt_FromLong(__pyx_v_numatoms); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 151; goto __pyx_L1;}
  __pyx_3 = PyInt_FromLong(__pyx_v_numframes); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 151; goto __pyx_L1;}
  __pyx_5 = PyInt_FromLong(3); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 151; goto __pyx_L1;}
  __pyx_6 = PyTuple_New(3); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 151; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_6, 0, __pyx_2);
  PyTuple_SET_ITEM(__pyx_6, 1, __pyx_3);
  PyTuple_SET_ITEM(__pyx_6, 2, __pyx_5);
  __pyx_2 = 0;
  __pyx_3 = 0;
  __pyx_5 = 0;
  __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_Numeric); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 151; goto __pyx_L1;}
  __pyx_3 = PyObject_GetAttr(__pyx_2, __pyx_n_Float64); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 151; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_5 = PyTuple_New(2); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 151; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_5, 0, __pyx_6);
  PyTuple_SET_ITEM(__pyx_5, 1, __pyx_3);
  __pyx_6 = 0;
  __pyx_3 = 0;
  __pyx_2 = PyObject_CallObject(__pyx_1, __pyx_5); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 151; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_5); __pyx_5 = 0;
  if (!__Pyx_TypeTest(__pyx_2, __pyx_ptype_8_dcdtest_ArrayType)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 151; goto __pyx_L1;}
  Py_DECREF(((PyObject *)__pyx_v_coord));
  __pyx_v_coord = ((PyArrayObject *)__pyx_2);
  __pyx_2 = 0;

  /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":152 */
  __pyx_6 = __Pyx_GetName(__pyx_m, __pyx_n_Numeric); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 152; goto __pyx_L1;}
  __pyx_3 = PyObject_GetAttr(__pyx_6, __pyx_n_zeros); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 152; goto __pyx_L1;}
  Py_DECREF(__pyx_6); __pyx_6 = 0;
  __pyx_1 = PyInt_FromLong(3); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 152; goto __pyx_L1;}
  __pyx_5 = PyInt_FromLong(__pyx_v_range); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 152; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(2); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 152; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_1);
  PyTuple_SET_ITEM(__pyx_2, 1, __pyx_5);
  __pyx_1 = 0;
  __pyx_5 = 0;
  __pyx_6 = __Pyx_GetName(__pyx_m, __pyx_n_Numeric); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 152; goto __pyx_L1;}
  __pyx_1 = PyObject_GetAttr(__pyx_6, __pyx_n_Float32); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 152; goto __pyx_L1;}
  Py_DECREF(__pyx_6); __pyx_6 = 0;
  __pyx_5 = PyTuple_New(2); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 152; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_5, 0, __pyx_2);
  PyTuple_SET_ITEM(__pyx_5, 1, __pyx_1);
  __pyx_2 = 0;
  __pyx_1 = 0;
  __pyx_6 = PyObject_CallObject(__pyx_3, __pyx_5); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 152; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_5); __pyx_5 = 0;
  if (!__Pyx_TypeTest(__pyx_6, __pyx_ptype_8_dcdtest_ArrayType)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 152; goto __pyx_L1;}
  Py_DECREF(((PyObject *)__pyx_v_temp));
  __pyx_v_temp = ((PyArrayObject *)__pyx_6);
  __pyx_6 = 0;

  /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":153 */
  __pyx_v_tempX = ((float (*))(__pyx_v_temp->data + (0 * (__pyx_v_temp->strides[0]))));

  /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":154 */
  __pyx_v_tempY = ((float (*))(__pyx_v_temp->data + (1 * (__pyx_v_temp->strides[0]))));

  /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":155 */
  __pyx_v_tempZ = ((float (*))(__pyx_v_temp->data + (2 * (__pyx_v_temp->strides[0]))));

  /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":157 */
  __pyx_v_rc = fio_fseek(__pyx_v_dcd->fd,__pyx_v_dcd->header_size,0);

  /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":158 */
  __pyx_v_dcd->setsread = 0;

  /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":159 */
  __pyx_v_dcd->first = 1;

  /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":164 */
  for (__pyx_v_i = 0; __pyx_v_i < __pyx_v_numframes; ++__pyx_v_i) {

    /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":165 */
    __pyx_4 = (__pyx_v_skip > 1);
    if (__pyx_4) {

      /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":168 */
      __pyx_v_numskip = ((__pyx_v_skip - (__pyx_v_dcd->setsread % __pyx_v_skip)) - 1);

      /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":169 */
      __pyx_v_rc = skip_dcdstep(__pyx_v_dcd->fd,__pyx_v_dcd->natoms,__pyx_v_dcd->nfixed,__pyx_v_dcd->charmm,__pyx_v_numskip);

      /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":170 */
      __pyx_4 = (__pyx_v_rc < 0);
      if (__pyx_4) {

        /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":171 */
        __pyx_2 = __Pyx_GetName(__pyx_b, __pyx_n_IOError); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 171; goto __pyx_L1;}
        __pyx_1 = PyTuple_New(1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 171; goto __pyx_L1;}
        Py_INCREF(__pyx_k7p);
        PyTuple_SET_ITEM(__pyx_1, 0, __pyx_k7p);
        __pyx_3 = PyObject_CallObject(__pyx_2, __pyx_1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 171; goto __pyx_L1;}
        Py_DECREF(__pyx_2); __pyx_2 = 0;
        Py_DECREF(__pyx_1); __pyx_1 = 0;
        __Pyx_Raise(__pyx_3, 0, 0);
        Py_DECREF(__pyx_3); __pyx_3 = 0;
        {__pyx_filename = __pyx_f[0]; __pyx_lineno = 171; goto __pyx_L1;}
        goto __pyx_L6;
      }
      __pyx_L6:;

      /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":172 */
      __pyx_v_dcd->setsread = (__pyx_v_dcd->setsread + __pyx_v_numskip);
      goto __pyx_L5;
    }
    __pyx_L5:;

    /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":173 */
    __pyx_v_rc = read_dcdsubset(__pyx_v_dcd->fd,__pyx_v_dcd->natoms,__pyx_v_lowerb,__pyx_v_upperb,__pyx_v_tempX,__pyx_v_tempY,__pyx_v_tempZ,__pyx_v_unitcell,__pyx_v_dcd->nfixed,__pyx_v_dcd->first,__pyx_v_dcd->freeind,__pyx_v_dcd->fixedcoords,__pyx_v_dcd->reverse,__pyx_v_dcd->charmm);

    /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":174 */
    __pyx_v_dcd->first = 0;

    /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":175 */
    __pyx_v_dcd->setsread = (__pyx_v_dcd->setsread + 1);

    /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":176 */
    __pyx_4 = (__pyx_v_rc < 0);
    if (__pyx_4) {

      /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":177 */
      __pyx_5 = __Pyx_GetName(__pyx_b, __pyx_n_IOError); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 177; goto __pyx_L1;}
      __pyx_6 = PyTuple_New(1); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 177; goto __pyx_L1;}
      Py_INCREF(__pyx_k8p);
      PyTuple_SET_ITEM(__pyx_6, 0, __pyx_k8p);
      __pyx_2 = PyObject_CallObject(__pyx_5, __pyx_6); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 177; goto __pyx_L1;}
      Py_DECREF(__pyx_5); __pyx_5 = 0;
      Py_DECREF(__pyx_6); __pyx_6 = 0;
      __Pyx_Raise(__pyx_2, 0, 0);
      Py_DECREF(__pyx_2); __pyx_2 = 0;
      {__pyx_filename = __pyx_f[0]; __pyx_lineno = 177; goto __pyx_L1;}
      goto __pyx_L7;
    }
    __pyx_L7:;

    /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":179 */
    for (__pyx_v_j = 0; __pyx_v_j < __pyx_v_numatoms; ++__pyx_v_j) {

      /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":180 */
      __pyx_v_index = ((((int (*))__pyx_v_atomlist->data)[__pyx_v_j]) - __pyx_v_lowerb);

      /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":181 */
      (((double (*))(((__pyx_v_coord->data + (__pyx_v_j * (__pyx_v_coord->strides[0]))) + (__pyx_v_i * (__pyx_v_coord->strides[1]))) + (0 * (__pyx_v_coord->strides[2]))))[0]) = (__pyx_v_tempX[__pyx_v_index]);

      /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":182 */
      (((double (*))(((__pyx_v_coord->data + (__pyx_v_j * (__pyx_v_coord->strides[0]))) + (__pyx_v_i * (__pyx_v_coord->strides[1]))) + (1 * (__pyx_v_coord->strides[2]))))[0]) = (__pyx_v_tempY[__pyx_v_index]);

      /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":183 */
      (((double (*))(((__pyx_v_coord->data + (__pyx_v_j * (__pyx_v_coord->strides[0]))) + (__pyx_v_i * (__pyx_v_coord->strides[1]))) + (2 * (__pyx_v_coord->strides[2]))))[0]) = (__pyx_v_tempZ[__pyx_v_index]);
      __pyx_L8:;
    }
    __pyx_L9:;
    __pyx_L3:;
  }
  __pyx_L4:;

  /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":184 */
  Py_INCREF(((PyObject *)__pyx_v_coord));
  __pyx_r = ((PyObject *)__pyx_v_coord);
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_5);
  Py_XDECREF(__pyx_6);
  __Pyx_AddTraceback("_dcdtest.__read_timeseries");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_atomlist);
  Py_DECREF(__pyx_v_coord);
  Py_DECREF(__pyx_v_temp);
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_atoms);
  return __pyx_r;
}

static int __pyx_f_8_dcdtest_jump_to_frame(__pyx_t_8_dcdtest_dcdhandle (*__pyx_v_dcd),int __pyx_v_frame) {
  int __pyx_r;
  int __pyx_1;

  /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":187 */
  __pyx_1 = (__pyx_v_frame > __pyx_v_dcd->nsets);
  if (__pyx_1) {
    __pyx_r = (-1);
    goto __pyx_L0;
    goto __pyx_L2;
  }
  __pyx_L2:;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_WriteUnraisable("_dcdtest.jump_to_frame");
  __pyx_L0:;
  return __pyx_r;
}

static __Pyx_InternTabEntry __pyx_intern_tab[] = {
  {&__pyx_n_Exception, "Exception"},
  {&__pyx_n_Float32, "Float32"},
  {&__pyx_n_Float64, "Float64"},
  {&__pyx_n_IOError, "IOError"},
  {&__pyx_n_Int32, "Int32"},
  {&__pyx_n_Numeric, "Numeric"},
  {&__pyx_n___read_timecorrel, "__read_timecorrel"},
  {&__pyx_n___read_timeseries, "__read_timeseries"},
  {&__pyx_n__dcd_C_ptr, "_dcd_C_ptr"},
  {&__pyx_n_array, "array"},
  {&__pyx_n_len, "len"},
  {&__pyx_n_zeros, "zeros"},
  {0, 0}
};

static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_k2p, __pyx_k2, sizeof(__pyx_k2)},
  {&__pyx_k3p, __pyx_k3, sizeof(__pyx_k3)},
  {&__pyx_k4p, __pyx_k4, sizeof(__pyx_k4)},
  {&__pyx_k5p, __pyx_k5, sizeof(__pyx_k5)},
  {&__pyx_k6p, __pyx_k6, sizeof(__pyx_k6)},
  {&__pyx_k7p, __pyx_k7, sizeof(__pyx_k7)},
  {&__pyx_k8p, __pyx_k8, sizeof(__pyx_k8)},
  {0, 0, 0}
};

static struct PyMethodDef __pyx_methods[] = {
  {"__read_timecorrel", (PyCFunction)__pyx_f_8_dcdtest___read_timecorrel, METH_VARARGS|METH_KEYWORDS, 0},
  {"__read_timeseries", (PyCFunction)__pyx_f_8_dcdtest___read_timeseries, METH_VARARGS|METH_KEYWORDS, 0},
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

PyMODINIT_FUNC init_dcdtest(void); /*proto*/
PyMODINIT_FUNC init_dcdtest(void) {
  PyObject *__pyx_1 = 0;
  __pyx_init_filenames();
  __pyx_m = Py_InitModule4("_dcdtest", __pyx_methods, 0, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; goto __pyx_L1;};
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; goto __pyx_L1;};
  if (__Pyx_InternStrings(__pyx_intern_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; goto __pyx_L1;};
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; goto __pyx_L1;};
  __pyx_ptype_8_dcdtest_ArrayType = __Pyx_ImportType("Numeric", "ArrayType", sizeof(PyArrayObject)); if (!__pyx_ptype_8_dcdtest_ArrayType) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 12; goto __pyx_L1;}

  /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":56 */
  __pyx_1 = __Pyx_Import(__pyx_n_Numeric, 0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_Numeric, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/Users/Naveen/Projects/python/code/MDAnalysis/src/dcdtest/_dcdtest.pyx":186 */
  return;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("_dcdtest");
}

static char *__pyx_filenames[] = {
  "_dcdtest.pyx",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list) {
    PyObject *__import__ = 0;
    PyObject *empty_list = 0;
    PyObject *module = 0;
    PyObject *global_dict = 0;
    PyObject *empty_dict = 0;
    PyObject *list;
    __import__ = PyObject_GetAttrString(__pyx_b, "__import__");
    if (!__import__)
        goto bad;
    if (from_list)
        list = from_list;
    else {
        empty_list = PyList_New(0);
        if (!empty_list)
            goto bad;
        list = empty_list;
    }
    global_dict = PyModule_GetDict(__pyx_m);
    if (!global_dict)
        goto bad;
    empty_dict = PyDict_New();
    if (!empty_dict)
        goto bad;
    module = PyObject_CallFunction(__import__, "OOOO",
        name, global_dict, empty_dict, list);
bad:
    Py_XDECREF(empty_list);
    Py_XDECREF(__import__);
    Py_XDECREF(empty_dict);
    return module;
}

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name) {
    PyObject *result;
    result = PyObject_GetAttr(dict, name);
    if (!result)
        PyErr_SetObject(PyExc_NameError, name);
    return result;
}

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb) {
    Py_XINCREF(type);
    Py_XINCREF(value);
    Py_XINCREF(tb);
    /* First, check the traceback argument, replacing None with NULL. */
    if (tb == Py_None) {
        Py_DECREF(tb);
        tb = 0;
    }
    else if (tb != NULL && !PyTraceBack_Check(tb)) {
        PyErr_SetString(PyExc_TypeError,
            "raise: arg 3 must be a traceback or None");
        goto raise_error;
    }
    /* Next, replace a missing value with None */
    if (value == NULL) {
        value = Py_None;
        Py_INCREF(value);
    }
    /* Next, repeatedly, replace a tuple exception with its first item */
    while (PyTuple_Check(type) && PyTuple_Size(type) > 0) {
        PyObject *tmp = type;
        type = PyTuple_GET_ITEM(type, 0);
        Py_INCREF(type);
        Py_DECREF(tmp);
    }
    if (PyString_Check(type))
        ;
    else if (PyClass_Check(type))
        ; /*PyErr_NormalizeException(&type, &value, &tb);*/
    else if (PyInstance_Check(type)) {
        /* Raising an instance.  The value should be a dummy. */
        if (value != Py_None) {
            PyErr_SetString(PyExc_TypeError,
              "instance exception may not have a separate value");
            goto raise_error;
        }
        else {
            /* Normalize to raise <class>, <instance> */
            Py_DECREF(value);
            value = type;
            type = (PyObject*) ((PyInstanceObject*)type)->in_class;
            Py_INCREF(type);
        }
    }
    else {
        /* Not something you can raise.  You get an exception
           anyway, just not what you specified :-) */
        PyErr_Format(PyExc_TypeError,
                 "exceptions must be strings, classes, or "
                 "instances, not %s", type->ob_type->tp_name);
        goto raise_error;
    }
    PyErr_Restore(type, value, tb);
    return;
raise_error:
    Py_XDECREF(value);
    Py_XDECREF(type);
    Py_XDECREF(tb);
    return;
}

static int __Pyx_TypeTest(PyObject *obj, PyTypeObject *type) {
    if (!type) {
        PyErr_Format(PyExc_SystemError, "Missing type object");
        return 0;
    }
    if (obj == Py_None || PyObject_TypeCheck(obj, type))
        return 1;
    PyErr_Format(PyExc_TypeError, "Cannot convert %s to %s",
        obj->ob_type->tp_name, type->tp_name);
    return 0;
}

static void __Pyx_WriteUnraisable(char *name) {
    PyObject *old_exc, *old_val, *old_tb;
    PyObject *ctx;
    PyErr_Fetch(&old_exc, &old_val, &old_tb);
    ctx = PyString_FromString(name);
    PyErr_Restore(old_exc, old_val, old_tb);
    if (!ctx)
        ctx = Py_None;
    PyErr_WriteUnraisable(ctx);
}

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t) {
    while (t->p) {
        *t->p = PyString_InternFromString(t->s);
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

static PyTypeObject *__Pyx_ImportType(char *module_name, char *class_name, 
    long size) 
{
    PyObject *py_module_name = 0;
    PyObject *py_class_name = 0;
    PyObject *py_name_list = 0;
    PyObject *py_module = 0;
    PyObject *result = 0;
    
    py_module_name = PyString_FromString(module_name);
    if (!py_module_name)
        goto bad;
    py_class_name = PyString_FromString(class_name);
    if (!py_class_name)
        goto bad;
    py_name_list = PyList_New(1);
    if (!py_name_list)
        goto bad;
    Py_INCREF(py_class_name);
    if (PyList_SetItem(py_name_list, 0, py_class_name) < 0)
        goto bad;
    py_module = __Pyx_Import(py_module_name, py_name_list);
    if (!py_module)
        goto bad;
    result = PyObject_GetAttr(py_module, py_class_name);
    if (!result)
        goto bad;
    if (!PyType_Check(result)) {
        PyErr_Format(PyExc_TypeError, 
            "%s.%s is not a type object",
            module_name, class_name);
        goto bad;
    }
    if (((PyTypeObject *)result)->tp_basicsize != size) {
        PyErr_Format(PyExc_ValueError, 
            "%s.%s does not appear to be the correct type object",
            module_name, class_name);
        goto bad;
    }
    goto done;
bad:
    Py_XDECREF(result);
    result = 0;
done:
    Py_XDECREF(py_module_name);
    Py_XDECREF(py_class_name);
    Py_XDECREF(py_name_list);
    return (PyTypeObject *)result;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_tuple = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;
    
    py_srcfile = PyString_FromString(__pyx_filename);
    if (!py_srcfile) goto bad;
    py_funcname = PyString_FromString(funcname);
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    empty_tuple = PyTuple_New(0);
    if (!empty_tuple) goto bad;
    empty_string = PyString_FromString("");
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        empty_tuple,  /*PyObject *consts,*/
        empty_tuple,  /*PyObject *names,*/
        empty_tuple,  /*PyObject *varnames,*/
        empty_tuple,  /*PyObject *freevars,*/
        empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_tuple);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}
