python_sources = [
'test_api.py',
'dummy.py',
'__init__.py',
'util.py',
'datafiles.py',
]

py3.install_sources(
  python_sources,
  subdir: 'MDAnalysisTests'
)

subdir('analysis')
subdir('data')
subdir('coordinates')
subdir('visualization')
subdir('core')
subdir('formats')
subdir('guesser')
subdir('lib')
subdir('transformations')
subdir('utils')
subdir('import')
subdir('topology')
subdir('converters')
subdir('auxiliary')
subdir('parallelism')
