py3.install_sources([
'__init__.py',
'backends.py',
'bat.py',
'contacts.py',
'density.py',
'dielectric.py',
'dihedrals.py',
'distances.py',
'helix_analysis.py',
'leaflet.py',
'nucleicacids.py',
'nuclinfo.py',
'pca.py',
'results.py',
'rms.py',
'gnm.py',
'lineardensity.py',
'psa.py',
'waterdynamics.py',
'base.py',
'rdf.py',
'align.py',
'atomicdistances.py',
'diffusionmap.py',
'msd.py',
'polymer.py',
  ],
  subdir: 'MDAnalysis/analysis'
)

subdir('data')
subdir('dssp')
subdir('hydrogenbonds')
subdir('encore')
subdir('hole2')
subdir('hbonds')
