python_sources = [
'1lpbA.pdb.gz',
'1lpbA.pdb.dssp',
'1i8nA.pdb.gz',
'1i8nA.pdb.dssp',
'1h4aX.pdb.gz',
'1h4aX.pdb.dssp',
'1eteA.pdb.gz',
'1eteA.pdb.dssp',
'1dx5I.pdb.gz',
'1dx5I.pdb.dssp',
'1bvyF.pdb.gz',
'1bvyF.pdb.dssp',
'1ahsA.pdb.gz',
'1ahsA.pdb.dssp',
'wrong_hydrogens.pdb.gz',
'README.md',
'4gcnA.pdb.gz',
'4gcnA.pdb.dssp',
'4dkcA.pdb.gz',
'4dkcA.pdb.dssp',
'3vjzA.pdb.gz',
'3vjzA.pdb.dssp',
'3t5gB.pdb.gz',
'3t5gB.pdb.dssp',
'3so6A.pdb.gz',
'3so6A.pdb.dssp',
'3q4oA.pdb.gz',
'3q4oA.pdb.dssp',
'3pivA.pdb.gz',
'3pivA.pdb.dssp',
'3on9A.pdb.gz',
'3on9A.pdb.dssp',
'3nzmA.pdb.gz',
'3nzmA.pdb.dssp',
'3ny7A.pdb.gz',
'3ny7A.pdb.dssp',
'3nngA.pdb.gz',
'3nngA.pdb.dssp',
'3nbkA.pdb.gz',
'3nbkA.pdb.dssp',
'3lqcA.pdb.gz',
'3lqcA.pdb.dssp',
'3l4rA.pdb.gz',
'3l4rA.pdb.dssp',
'3k7pA.pdb.gz',
'3k7pA.pdb.dssp',
'3ii2A.pdb.gz',
'3ii2A.pdb.dssp',
'3ieyB.pdb.gz',
'3ieyB.pdb.dssp',
'3hklA.pdb.gz',
'3hklA.pdb.dssp',
'3gwiA.pdb.gz',
'3gwiA.pdb.dssp',
'3gknA.pdb.gz',
'3gknA.pdb.dssp',
'3gfsA.pdb.gz',
'3gfsA.pdb.dssp',
'3fhkA.pdb.gz',
'3fhkA.pdb.dssp',
'3ejfA.pdb.gz',
'3ejfA.pdb.dssp',
'3e8mA.pdb.gz',
'3e8mA.pdb.dssp',
'3aqgA.pdb.gz',
'3aqgA.pdb.dssp',
'3a4rA.pdb.gz',
'3a4rA.pdb.dssp',
'2xr6A.pdb.gz',
'2xr6A.pdb.dssp',
'2xdgA.pdb.gz',
'2xdgA.pdb.dssp',
'2xcjA.pdb.gz',
'2xcjA.pdb.dssp',
'2va0A.pdb.gz',
'2va0A.pdb.dssp',
'2qdlA.pdb.gz',
'2qdlA.pdb.dssp',
'2j49A.pdb.gz',
'2j49A.pdb.dssp',
'2i39A.pdb.gz',
'2i39A.pdb.dssp',
'2gu3A.pdb.gz',
'2gu3A.pdb.dssp',
'2fvvA.pdb.gz',
'2fvvA.pdb.dssp',
'2cviA.pdb.gz',
'2cviA.pdb.dssp',
'2cayA.pdb.gz',
'2cayA.pdb.dssp',
'2a2lA.pdb.gz',
'2a2lA.pdb.dssp',
'1y1lA.pdb.gz',
'1y1lA.pdb.dssp',
'1v7mV.pdb.gz',
'1v7mV.pdb.dssp',
'1pdoA.pdb.gz',
'1pdoA.pdb.dssp',
'1or4A.pdb.gz',
'1or4A.pdb.dssp',
'1mr1D.pdb.gz',
'1mr1D.pdb.dssp',
'1mr1D_failing.pdb.gz',
]

py3.install_sources(
  python_sources,
  subdir: 'MDAnalysisTests/data/dssp'
)

