/* Generated by Pyrex 0.9.3 on Wed Sep 14 15:56:27 2005 */

#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#include "Numeric/arrayobject.h"
#include "tess.h"
#include "math.h"
#include "stdio.h"


typedef struct {PyObject **p; char *s;} __Pyx_InternTabEntry; /*proto*/
typedef struct {PyObject **p; char *s; long n;} __Pyx_StringTabEntry; /*proto*/
static PyObject *__Pyx_UnpackItem(PyObject *, int); /*proto*/
static int __Pyx_EndUnpack(PyObject *, int); /*proto*/
static int __Pyx_PrintItem(PyObject *); /*proto*/
static int __Pyx_PrintNewline(void); /*proto*/
static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb); /*proto*/
static void __Pyx_ReRaise(void); /*proto*/
static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list); /*proto*/
static PyObject *__Pyx_GetExcValue(void); /*proto*/
static int __Pyx_ArgTypeTest(PyObject *obj, PyTypeObject *type, int none_allowed, char *name); /*proto*/
static int __Pyx_TypeTest(PyObject *obj, PyTypeObject *type); /*proto*/
static int __Pyx_GetStarArgs(PyObject **args, PyObject **kwds, char *kwd_list[], int nargs, PyObject **args2, PyObject **kwds2); /*proto*/
static void __Pyx_WriteUnraisable(char *name); /*proto*/
static void __Pyx_AddTraceback(char *funcname); /*proto*/
static PyTypeObject *__Pyx_ImportType(char *module_name, char *class_name, long size);  /*proto*/
static int __Pyx_SetVtable(PyObject *dict, void *vtable); /*proto*/
static int __Pyx_GetVtable(PyObject *dict, void *vtabptr); /*proto*/
static PyObject *__Pyx_CreateClass(PyObject *bases, PyObject *dict, PyObject *name, char *modname); /*proto*/
static int __Pyx_InternStrings(__Pyx_InternTabEntry *t); /*proto*/
static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/
static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name); /*proto*/

static PyObject *__pyx_m;
static PyObject *__pyx_b;
static int __pyx_lineno;
static char *__pyx_filename;
staticforward char **__pyx_f;

/* Declarations from _delaunay */

static PyTypeObject *__pyx_ptype_9_delaunay_ArrayType = 0;

/* Implementation of _delaunay */


static PyObject *__pyx_n_Numeric;
static PyObject *__pyx_n_circumcircles;
static PyObject *__pyx_n_triangulate;

static PyObject *__pyx_n_zeros;
static PyObject *__pyx_n_Float64;
static PyObject *__pyx_n_Exception;

static PyObject *__pyx_k2p;

static char (__pyx_k2[]) = "Some points are collinear!";

static PyObject *__pyx_f_9_delaunay_circumcircles(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_9_delaunay_circumcircles(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyArrayObject *__pyx_v_vertices = 0;
  PyArrayObject *__pyx_v_triangles = 0;
  integer (*__pyx_v_tri);
  real (*__pyx_v_v);
  real (*__pyx_v_c);
  real (*__pyx_v_r);
  real (*__pyx_v_v0);
  real (*__pyx_v_v1);
  real (*__pyx_v_v2);
  real __pyx_v_xd0;
  real __pyx_v_yd0;
  real __pyx_v_xa0;
  real __pyx_v_ya0;
  double __pyx_v_a2;
  double __pyx_v_b2;
  double __pyx_v_numerator;
  double __pyx_v_denominator;
  real __pyx_v_centerx;
  real __pyx_v_centery;
  real __pyx_v_radius;
  PyArrayObject *__pyx_v_centers;
  PyArrayObject *__pyx_v_rad;
  int __pyx_v_i;
  int __pyx_v_numtri;
  int __pyx_v_dimtri;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  int __pyx_5;
  static char *__pyx_argnames[] = {"vertices","triangles",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OO", __pyx_argnames, &__pyx_v_vertices, &__pyx_v_triangles)) return 0;
  Py_INCREF(__pyx_v_vertices);
  Py_INCREF(__pyx_v_triangles);
  ((PyObject*)__pyx_v_centers) = Py_None; Py_INCREF(((PyObject*)__pyx_v_centers));
  ((PyObject*)__pyx_v_rad) = Py_None; Py_INCREF(((PyObject*)__pyx_v_rad));
  if (!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_vertices), __pyx_ptype_9_delaunay_ArrayType, 1, "vertices")) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 32; goto __pyx_L1;}
  if (!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_triangles), __pyx_ptype_9_delaunay_ArrayType, 1, "triangles")) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 32; goto __pyx_L1;}

  /* "/Users/Naveen/Desktop/MDToolsMarch97/dcdread/src/delaunay/_delaunay.pyx":42 */
  __pyx_v_numtri = (__pyx_v_triangles->dimensions[0]);

  /* "/Users/Naveen/Desktop/MDToolsMarch97/dcdread/src/delaunay/_delaunay.pyx":43 */
  __pyx_v_dimtri = (__pyx_v_triangles->dimensions[1]);

  /* "/Users/Naveen/Desktop/MDToolsMarch97/dcdread/src/delaunay/_delaunay.pyx":44 */
  __pyx_v_v = ((real (*))__pyx_v_vertices->data);

  /* "/Users/Naveen/Desktop/MDToolsMarch97/dcdread/src/delaunay/_delaunay.pyx":45 */
  __pyx_v_tri = ((integer (*))__pyx_v_triangles->data);

  /* "/Users/Naveen/Desktop/MDToolsMarch97/dcdread/src/delaunay/_delaunay.pyx":46 */
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_Numeric); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 46; goto __pyx_L1;}
  __pyx_2 = PyObject_GetAttr(__pyx_1, __pyx_n_zeros); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 46; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyInt_FromLong(__pyx_v_numtri); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 46; goto __pyx_L1;}
  __pyx_3 = PyInt_FromLong(2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 46; goto __pyx_L1;}
  __pyx_4 = PyTuple_New(2); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 46; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_4, 0, __pyx_1);
  PyTuple_SET_ITEM(__pyx_4, 1, __pyx_3);
  __pyx_1 = 0;
  __pyx_3 = 0;
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_Numeric); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 46; goto __pyx_L1;}
  __pyx_3 = PyObject_GetAttr(__pyx_1, __pyx_n_Float64); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 46; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyTuple_New(2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 46; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_1, 0, __pyx_4);
  PyTuple_SET_ITEM(__pyx_1, 1, __pyx_3);
  __pyx_4 = 0;
  __pyx_3 = 0;
  __pyx_4 = PyObject_CallObject(__pyx_2, __pyx_1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 46; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  if (!__Pyx_TypeTest(__pyx_4, __pyx_ptype_9_delaunay_ArrayType)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 46; goto __pyx_L1;}
  Py_DECREF(((PyObject *)__pyx_v_centers));
  ((PyObject *)__pyx_v_centers) = __pyx_4;
  __pyx_4 = 0;

  /* "/Users/Naveen/Desktop/MDToolsMarch97/dcdread/src/delaunay/_delaunay.pyx":47 */
  __pyx_3 = __Pyx_GetName(__pyx_m, __pyx_n_Numeric); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 47; goto __pyx_L1;}
  __pyx_2 = PyObject_GetAttr(__pyx_3, __pyx_n_zeros); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 47; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_1 = PyInt_FromLong(__pyx_v_numtri); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 47; goto __pyx_L1;}
  __pyx_4 = __Pyx_GetName(__pyx_m, __pyx_n_Numeric); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 47; goto __pyx_L1;}
  __pyx_3 = PyObject_GetAttr(__pyx_4, __pyx_n_Float64); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 47; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  __pyx_4 = PyTuple_New(2); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 47; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_4, 0, __pyx_1);
  PyTuple_SET_ITEM(__pyx_4, 1, __pyx_3);
  __pyx_1 = 0;
  __pyx_3 = 0;
  __pyx_1 = PyObject_CallObject(__pyx_2, __pyx_4); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 47; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  if (!__Pyx_TypeTest(__pyx_1, __pyx_ptype_9_delaunay_ArrayType)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 47; goto __pyx_L1;}
  Py_DECREF(((PyObject *)__pyx_v_rad));
  ((PyObject *)__pyx_v_rad) = __pyx_1;
  __pyx_1 = 0;

  /* "/Users/Naveen/Desktop/MDToolsMarch97/dcdread/src/delaunay/_delaunay.pyx":48 */
  __pyx_v_c = ((real (*))__pyx_v_centers->data);

  /* "/Users/Naveen/Desktop/MDToolsMarch97/dcdread/src/delaunay/_delaunay.pyx":49 */
  __pyx_v_r = ((real (*))__pyx_v_rad->data);

  /* "/Users/Naveen/Desktop/MDToolsMarch97/dcdread/src/delaunay/_delaunay.pyx":52 */
  for (__pyx_v_i = 0; __pyx_v_i < __pyx_v_numtri; ++__pyx_v_i) {

    /* "/Users/Naveen/Desktop/MDToolsMarch97/dcdread/src/delaunay/_delaunay.pyx":53 */
    __pyx_v_v0 = (&(__pyx_v_v[((__pyx_v_tri[((__pyx_v_i * __pyx_v_dimtri) + 0)]) * 2)]));

    /* "/Users/Naveen/Desktop/MDToolsMarch97/dcdread/src/delaunay/_delaunay.pyx":54 */
    __pyx_v_v1 = (&(__pyx_v_v[((__pyx_v_tri[((__pyx_v_i * __pyx_v_dimtri) + 1)]) * 2)]));

    /* "/Users/Naveen/Desktop/MDToolsMarch97/dcdread/src/delaunay/_delaunay.pyx":55 */
    __pyx_v_v2 = (&(__pyx_v_v[((__pyx_v_tri[((__pyx_v_i * __pyx_v_dimtri) + 2)]) * 2)]));

    /* "/Users/Naveen/Desktop/MDToolsMarch97/dcdread/src/delaunay/_delaunay.pyx":56 */
    __pyx_v_xd0 = ((__pyx_v_v1[0]) - (__pyx_v_v0[0]));

    /* "/Users/Naveen/Desktop/MDToolsMarch97/dcdread/src/delaunay/_delaunay.pyx":57 */
    __pyx_v_yd0 = ((__pyx_v_v1[1]) - (__pyx_v_v0[1]));

    /* "/Users/Naveen/Desktop/MDToolsMarch97/dcdread/src/delaunay/_delaunay.pyx":58 */
    __pyx_v_xa0 = ((__pyx_v_v2[0]) - (__pyx_v_v0[0]));

    /* "/Users/Naveen/Desktop/MDToolsMarch97/dcdread/src/delaunay/_delaunay.pyx":59 */
    __pyx_v_ya0 = ((__pyx_v_v2[1]) - (__pyx_v_v0[1]));

    /* "/Users/Naveen/Desktop/MDToolsMarch97/dcdread/src/delaunay/_delaunay.pyx":61 */
    __pyx_v_a2 = ((__pyx_v_xd0 * __pyx_v_xd0) + (__pyx_v_yd0 * __pyx_v_yd0));

    /* "/Users/Naveen/Desktop/MDToolsMarch97/dcdread/src/delaunay/_delaunay.pyx":62 */
    __pyx_v_b2 = ((__pyx_v_xa0 * __pyx_v_xa0) + (__pyx_v_ya0 * __pyx_v_ya0));

    /* "/Users/Naveen/Desktop/MDToolsMarch97/dcdread/src/delaunay/_delaunay.pyx":63 */
    __pyx_v_numerator = ((__pyx_v_xd0 * __pyx_v_ya0) - (__pyx_v_xa0 * __pyx_v_yd0));

    /* "/Users/Naveen/Desktop/MDToolsMarch97/dcdread/src/delaunay/_delaunay.pyx":64 */
    __pyx_5 = (!(__pyx_v_numerator == 0));
    if (__pyx_5) {
      __pyx_v_denominator = (0.5 / __pyx_v_numerator);
      goto __pyx_L4;
    }
    /*else*/ {
      __pyx_3 = __Pyx_GetName(__pyx_b, __pyx_n_Exception); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 65; goto __pyx_L1;}
      __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 65; goto __pyx_L1;}
      Py_INCREF(__pyx_k2p);
      PyTuple_SET_ITEM(__pyx_2, 0, __pyx_k2p);
      __pyx_4 = PyObject_CallObject(__pyx_3, __pyx_2); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 65; goto __pyx_L1;}
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      Py_DECREF(__pyx_2); __pyx_2 = 0;
      __Pyx_Raise(__pyx_4, 0, 0);
      Py_DECREF(__pyx_4); __pyx_4 = 0;
      {__pyx_filename = __pyx_f[0]; __pyx_lineno = 65; goto __pyx_L1;}
    }
    __pyx_L4:;

    /* "/Users/Naveen/Desktop/MDToolsMarch97/dcdread/src/delaunay/_delaunay.pyx":67 */
    __pyx_v_centerx = ((__pyx_v_v0[0]) - (((__pyx_v_yd0 * __pyx_v_b2) - (__pyx_v_ya0 * __pyx_v_a2)) * __pyx_v_denominator));

    /* "/Users/Naveen/Desktop/MDToolsMarch97/dcdread/src/delaunay/_delaunay.pyx":68 */
    __pyx_v_centery = ((__pyx_v_v0[1]) + (((__pyx_v_xd0 * __pyx_v_b2) - (__pyx_v_xa0 * __pyx_v_a2)) * __pyx_v_denominator));

    /* "/Users/Naveen/Desktop/MDToolsMarch97/dcdread/src/delaunay/_delaunay.pyx":69 */
    (__pyx_v_c[((__pyx_v_i * 2) + 0)]) = __pyx_v_centerx;

    /* "/Users/Naveen/Desktop/MDToolsMarch97/dcdread/src/delaunay/_delaunay.pyx":70 */
    (__pyx_v_c[((__pyx_v_i * 2) + 1)]) = __pyx_v_centery;

    /* "/Users/Naveen/Desktop/MDToolsMarch97/dcdread/src/delaunay/_delaunay.pyx":71 */
    (__pyx_v_r[__pyx_v_i]) = sqrt((((__pyx_v_centerx - (__pyx_v_v0[0])) * (__pyx_v_centerx - (__pyx_v_v0[0]))) + ((__pyx_v_centery - (__pyx_v_v0[1])) * (__pyx_v_centery - (__pyx_v_v0[1])))));
    __pyx_L2:;
  }
  __pyx_L3:;

  /* "/Users/Naveen/Desktop/MDToolsMarch97/dcdread/src/delaunay/_delaunay.pyx":73 */
  __pyx_1 = PyTuple_New(2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 73; goto __pyx_L1;}
  Py_INCREF(((PyObject *)__pyx_v_centers));
  PyTuple_SET_ITEM(__pyx_1, 0, ((PyObject *)__pyx_v_centers));
  Py_INCREF(((PyObject *)__pyx_v_rad));
  PyTuple_SET_ITEM(__pyx_1, 1, ((PyObject *)__pyx_v_rad));
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("_delaunay.circumcircles");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_centers);
  Py_DECREF(__pyx_v_rad);
  Py_DECREF(__pyx_v_vertices);
  Py_DECREF(__pyx_v_triangles);
  return __pyx_r;
}

static PyObject *__pyx_n_Int;

static PyObject *__pyx_k3p;
static PyObject *__pyx_k4p;

static char (__pyx_k3[]) = "_delaunay triangulation: incorrect number of dimensions";
static char (__pyx_k4[]) = "Error in tesselation: error %d, ns %d";

static PyObject *__pyx_f_9_delaunay_triangulate(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_9_delaunay_triangulate(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyArrayObject *__pyx_v_points = 0;
  integer __pyx_v_mrowp;
  integer __pyx_v_mp;
  integer __pyx_v_np;
  integer __pyx_v_mrows;
  integer __pyx_v_ncols;
  integer __pyx_v_ms;
  integer __pyx_v_ns;
  integer __pyx_v_ierr;
  integer __pyx_v_liw;
  integer __pyx_v_llfact;
  PyArrayObject *__pyx_v_iwork;
  PyArrayObject *__pyx_v_work;
  PyArrayObject *__pyx_v_nsim;
  PyArrayObject *__pyx_v_nadj;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  static char *__pyx_argnames[] = {"points",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_points)) return 0;
  Py_INCREF(__pyx_v_points);
  ((PyObject*)__pyx_v_iwork) = Py_None; Py_INCREF(((PyObject*)__pyx_v_iwork));
  ((PyObject*)__pyx_v_work) = Py_None; Py_INCREF(((PyObject*)__pyx_v_work));
  ((PyObject*)__pyx_v_nsim) = Py_None; Py_INCREF(((PyObject*)__pyx_v_nsim));
  ((PyObject*)__pyx_v_nadj) = Py_None; Py_INCREF(((PyObject*)__pyx_v_nadj));
  if (!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_points), __pyx_ptype_9_delaunay_ArrayType, 1, "points")) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 75; goto __pyx_L1;}

  /* "/Users/Naveen/Desktop/MDToolsMarch97/dcdread/src/delaunay/_delaunay.pyx":83 */
  __pyx_1 = (__pyx_v_points->nd != 2);
  if (__pyx_1) {
    __pyx_2 = __Pyx_GetName(__pyx_b, __pyx_n_Exception); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 83; goto __pyx_L1;}
    __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 83; goto __pyx_L1;}
    Py_INCREF(__pyx_k3p);
    PyTuple_SET_ITEM(__pyx_3, 0, __pyx_k3p);
    __pyx_4 = PyObject_CallObject(__pyx_2, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 83; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __Pyx_Raise(__pyx_4, 0, 0);
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 83; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/Users/Naveen/Desktop/MDToolsMarch97/dcdread/src/delaunay/_delaunay.pyx":84 */
  __pyx_v_np = (__pyx_v_points->dimensions[0]);

  /* "/Users/Naveen/Desktop/MDToolsMarch97/dcdread/src/delaunay/_delaunay.pyx":85 */
  __pyx_1 = (__pyx_v_points->dimensions[1]);
  __pyx_v_mrowp = __pyx_1;
  __pyx_v_mp = __pyx_1;

  /* "/Users/Naveen/Desktop/MDToolsMarch97/dcdread/src/delaunay/_delaunay.pyx":86 */
  __pyx_v_ierr = 0;

  /* "/Users/Naveen/Desktop/MDToolsMarch97/dcdread/src/delaunay/_delaunay.pyx":87 */
  __pyx_v_ms = (__pyx_v_mp + 1);

  /* "/Users/Naveen/Desktop/MDToolsMarch97/dcdread/src/delaunay/_delaunay.pyx":88 */
  __pyx_v_mrows = (__pyx_v_mrowp + 1);

  /* "/Users/Naveen/Desktop/MDToolsMarch97/dcdread/src/delaunay/_delaunay.pyx":89 */
  __pyx_v_ncols = (12 * __pyx_v_np);

  /* "/Users/Naveen/Desktop/MDToolsMarch97/dcdread/src/delaunay/_delaunay.pyx":90 */
  __pyx_v_llfact = 20;

  /* "/Users/Naveen/Desktop/MDToolsMarch97/dcdread/src/delaunay/_delaunay.pyx":91 */
  __pyx_v_liw = ((7 * __pyx_v_llfact) * __pyx_v_np);

  /* "/Users/Naveen/Desktop/MDToolsMarch97/dcdread/src/delaunay/_delaunay.pyx":92 */
  __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_Numeric); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 92; goto __pyx_L1;}
  __pyx_3 = PyObject_GetAttr(__pyx_2, __pyx_n_zeros); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 92; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_4 = PyInt_FromLong(__pyx_v_liw); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 92; goto __pyx_L1;}
  __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_Numeric); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 92; goto __pyx_L1;}
  __pyx_5 = PyObject_GetAttr(__pyx_2, __pyx_n_Int); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 92; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_2 = PyTuple_New(2); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 92; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_4);
  PyTuple_SET_ITEM(__pyx_2, 1, __pyx_5);
  __pyx_4 = 0;
  __pyx_5 = 0;
  __pyx_4 = PyObject_CallObject(__pyx_3, __pyx_2); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 92; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  if (!__Pyx_TypeTest(__pyx_4, __pyx_ptype_9_delaunay_ArrayType)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 92; goto __pyx_L1;}
  Py_DECREF(((PyObject *)__pyx_v_iwork));
  ((PyObject *)__pyx_v_iwork) = __pyx_4;
  __pyx_4 = 0;

  /* "/Users/Naveen/Desktop/MDToolsMarch97/dcdread/src/delaunay/_delaunay.pyx":93 */
  __pyx_5 = __Pyx_GetName(__pyx_m, __pyx_n_Numeric); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 93; goto __pyx_L1;}
  __pyx_3 = PyObject_GetAttr(__pyx_5, __pyx_n_zeros); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 93; goto __pyx_L1;}
  Py_DECREF(__pyx_5); __pyx_5 = 0;
  __pyx_2 = PyInt_FromLong(((5 * __pyx_v_mrowp) + (__pyx_v_mrowp * __pyx_v_mrowp))); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 93; goto __pyx_L1;}
  __pyx_4 = __Pyx_GetName(__pyx_m, __pyx_n_Numeric); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 93; goto __pyx_L1;}
  __pyx_5 = PyObject_GetAttr(__pyx_4, __pyx_n_Float64); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 93; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  __pyx_4 = PyTuple_New(2); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 93; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_4, 0, __pyx_2);
  PyTuple_SET_ITEM(__pyx_4, 1, __pyx_5);
  __pyx_2 = 0;
  __pyx_5 = 0;
  __pyx_2 = PyObject_CallObject(__pyx_3, __pyx_4); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 93; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  if (!__Pyx_TypeTest(__pyx_2, __pyx_ptype_9_delaunay_ArrayType)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 93; goto __pyx_L1;}
  Py_DECREF(((PyObject *)__pyx_v_work));
  ((PyObject *)__pyx_v_work) = __pyx_2;
  __pyx_2 = 0;

  /* "/Users/Naveen/Desktop/MDToolsMarch97/dcdread/src/delaunay/_delaunay.pyx":94 */
  __pyx_5 = __Pyx_GetName(__pyx_m, __pyx_n_Numeric); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; goto __pyx_L1;}
  __pyx_3 = PyObject_GetAttr(__pyx_5, __pyx_n_zeros); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; goto __pyx_L1;}
  Py_DECREF(__pyx_5); __pyx_5 = 0;
  __pyx_4 = PyInt_FromLong(__pyx_v_ncols); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; goto __pyx_L1;}
  __pyx_2 = PyInt_FromLong(__pyx_v_mrows); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; goto __pyx_L1;}
  __pyx_5 = PyTuple_New(2); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_5, 0, __pyx_4);
  PyTuple_SET_ITEM(__pyx_5, 1, __pyx_2);
  __pyx_4 = 0;
  __pyx_2 = 0;
  __pyx_4 = __Pyx_GetName(__pyx_m, __pyx_n_Numeric); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; goto __pyx_L1;}
  __pyx_2 = PyObject_GetAttr(__pyx_4, __pyx_n_Int); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  __pyx_4 = PyTuple_New(2); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_4, 0, __pyx_5);
  PyTuple_SET_ITEM(__pyx_4, 1, __pyx_2);
  __pyx_5 = 0;
  __pyx_2 = 0;
  __pyx_5 = PyObject_CallObject(__pyx_3, __pyx_4); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  if (!__Pyx_TypeTest(__pyx_5, __pyx_ptype_9_delaunay_ArrayType)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; goto __pyx_L1;}
  Py_DECREF(((PyObject *)__pyx_v_nsim));
  ((PyObject *)__pyx_v_nsim) = __pyx_5;
  __pyx_5 = 0;

  /* "/Users/Naveen/Desktop/MDToolsMarch97/dcdread/src/delaunay/_delaunay.pyx":95 */
  __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_Numeric); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; goto __pyx_L1;}
  __pyx_3 = PyObject_GetAttr(__pyx_2, __pyx_n_zeros); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_4 = PyInt_FromLong(__pyx_v_ncols); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; goto __pyx_L1;}
  __pyx_5 = PyInt_FromLong(__pyx_v_mrows); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(2); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_4);
  PyTuple_SET_ITEM(__pyx_2, 1, __pyx_5);
  __pyx_4 = 0;
  __pyx_5 = 0;
  __pyx_4 = __Pyx_GetName(__pyx_m, __pyx_n_Numeric); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; goto __pyx_L1;}
  __pyx_5 = PyObject_GetAttr(__pyx_4, __pyx_n_Int); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  __pyx_4 = PyTuple_New(2); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_4, 0, __pyx_2);
  PyTuple_SET_ITEM(__pyx_4, 1, __pyx_5);
  __pyx_2 = 0;
  __pyx_5 = 0;
  __pyx_2 = PyObject_CallObject(__pyx_3, __pyx_4); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  if (!__Pyx_TypeTest(__pyx_2, __pyx_ptype_9_delaunay_ArrayType)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; goto __pyx_L1;}
  Py_DECREF(((PyObject *)__pyx_v_nadj));
  ((PyObject *)__pyx_v_nadj) = __pyx_2;
  __pyx_2 = 0;

  /* "/Users/Naveen/Desktop/MDToolsMarch97/dcdread/src/delaunay/_delaunay.pyx":96 */
  tess_((&__pyx_v_mrowp),(&__pyx_v_mp),(&__pyx_v_np),((real (*))__pyx_v_points->data),(&__pyx_v_mrows),(&__pyx_v_ncols),(&__pyx_v_ms),(&__pyx_v_ns),((integer (*))__pyx_v_nsim->data),((integer (*))__pyx_v_nadj->data),((real (*))__pyx_v_work->data),(&__pyx_v_llfact),((integer (*))__pyx_v_iwork->data),(&__pyx_v_ierr));

  /* "/Users/Naveen/Desktop/MDToolsMarch97/dcdread/src/delaunay/_delaunay.pyx":97 */
  __pyx_1 = (__pyx_v_ierr != 0);
  if (__pyx_1) {

    /* "/Users/Naveen/Desktop/MDToolsMarch97/dcdread/src/delaunay/_delaunay.pyx":99 */
    __pyx_5 = __Pyx_GetName(__pyx_b, __pyx_n_Exception); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 99; goto __pyx_L1;}
    __pyx_3 = PyInt_FromLong(__pyx_v_ierr); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 99; goto __pyx_L1;}
    __pyx_4 = PyInt_FromLong(__pyx_v_ns); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 99; goto __pyx_L1;}
    __pyx_2 = PyTuple_New(2); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 99; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_2, 0, __pyx_3);
    PyTuple_SET_ITEM(__pyx_2, 1, __pyx_4);
    __pyx_3 = 0;
    __pyx_4 = 0;
    __pyx_3 = PyNumber_Remainder(__pyx_k4p, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 99; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_4 = PyTuple_New(1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 99; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_4, 0, __pyx_3);
    __pyx_3 = 0;
    __pyx_2 = PyObject_CallObject(__pyx_5, __pyx_4); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 99; goto __pyx_L1;}
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __Pyx_Raise(__pyx_2, 0, 0);
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 99; goto __pyx_L1;}
    goto __pyx_L3;
  }
  __pyx_L3:;

  /* "/Users/Naveen/Desktop/MDToolsMarch97/dcdread/src/delaunay/_delaunay.pyx":100 */
  __pyx_3 = PySequence_GetSlice(((PyObject *)__pyx_v_nsim), 0, __pyx_v_ns); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 100; goto __pyx_L1;}
  __pyx_5 = PySequence_GetSlice(((PyObject *)__pyx_v_nadj), 0, __pyx_v_ns); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 100; goto __pyx_L1;}
  __pyx_4 = PyTuple_New(2); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 100; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_4, 0, __pyx_3);
  PyTuple_SET_ITEM(__pyx_4, 1, __pyx_5);
  __pyx_3 = 0;
  __pyx_5 = 0;
  __pyx_r = __pyx_4;
  __pyx_4 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  __Pyx_AddTraceback("_delaunay.triangulate");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_iwork);
  Py_DECREF(__pyx_v_work);
  Py_DECREF(__pyx_v_nsim);
  Py_DECREF(__pyx_v_nadj);
  Py_DECREF(__pyx_v_points);
  return __pyx_r;
}

static __Pyx_InternTabEntry __pyx_intern_tab[] = {
  {&__pyx_n_Exception, "Exception"},
  {&__pyx_n_Float64, "Float64"},
  {&__pyx_n_Int, "Int"},
  {&__pyx_n_Numeric, "Numeric"},
  {&__pyx_n_circumcircles, "circumcircles"},
  {&__pyx_n_triangulate, "triangulate"},
  {&__pyx_n_zeros, "zeros"},
  {0, 0}
};

static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_k2p, __pyx_k2, sizeof(__pyx_k2)},
  {&__pyx_k3p, __pyx_k3, sizeof(__pyx_k3)},
  {&__pyx_k4p, __pyx_k4, sizeof(__pyx_k4)},
  {0, 0, 0}
};

static struct PyMethodDef __pyx_methods[] = {
  {"circumcircles", (PyCFunction)__pyx_f_9_delaunay_circumcircles, METH_VARARGS|METH_KEYWORDS, 0},
  {"triangulate", (PyCFunction)__pyx_f_9_delaunay_triangulate, METH_VARARGS|METH_KEYWORDS, 0},
  {0, 0, 0, 0}
};

DL_EXPORT(void) init_delaunay(void); /*proto*/
DL_EXPORT(void) init_delaunay(void) {
  PyObject *__pyx_1 = 0;
  __pyx_m = Py_InitModule4("_delaunay", __pyx_methods, 0, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; goto __pyx_L1;};
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; goto __pyx_L1;};
  if (__Pyx_InternStrings(__pyx_intern_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; goto __pyx_L1;};
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; goto __pyx_L1;};
  __pyx_ptype_9_delaunay_ArrayType = __Pyx_ImportType("Numeric", "ArrayType", sizeof(PyArrayObject)); if (!__pyx_ptype_9_delaunay_ArrayType) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 9; goto __pyx_L1;}

  /* "/Users/Naveen/Desktop/MDToolsMarch97/dcdread/src/delaunay/_delaunay.pyx":17 */
  __pyx_1 = __Pyx_Import(__pyx_n_Numeric, 0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 17; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_Numeric, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 17; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/Users/Naveen/Desktop/MDToolsMarch97/dcdread/src/delaunay/_delaunay.pyx":75 */
  return;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("_delaunay");
}

static char *__pyx_filenames[] = {
  "_delaunay.pyx",
};
statichere char **__pyx_f = __pyx_filenames;

/* Runtime support code */

static int __Pyx_ArgTypeTest(PyObject *obj, PyTypeObject *type, int none_allowed, char *name) {
    if (!type) {
        PyErr_Format(PyExc_SystemError, "Missing type object");
        return 0;
    }
    if ((none_allowed && obj == Py_None) || PyObject_TypeCheck(obj, type))
        return 1;
    PyErr_Format(PyExc_TypeError,
        "Argument '%s' has incorrect type (expected %s, got %s)",
        name, type->tp_name, obj->ob_type->tp_name);
    return 0;
}

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list) {
    PyObject *__import__ = 0;
    PyObject *empty_list = 0;
    PyObject *module = 0;
    PyObject *global_dict = 0;
    PyObject *empty_dict = 0;
    PyObject *list;
    __import__ = PyObject_GetAttrString(__pyx_b, "__import__");
    if (!__import__)
        goto bad;
    if (from_list)
        list = from_list;
    else {
        empty_list = PyList_New(0);
        if (!empty_list)
            goto bad;
        list = empty_list;
    }
    global_dict = PyModule_GetDict(__pyx_m);
    if (!global_dict)
        goto bad;
    empty_dict = PyDict_New();
    if (!empty_dict)
        goto bad;
    module = PyObject_CallFunction(__import__, "OOOO",
        name, global_dict, empty_dict, list);
bad:
    Py_XDECREF(empty_list);
    Py_XDECREF(__import__);
    Py_XDECREF(empty_dict);
    return module;
}

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name) {
    PyObject *result;
    result = PyObject_GetAttr(dict, name);
    if (!result)
        PyErr_SetObject(PyExc_NameError, name);
    return result;
}

static int __Pyx_TypeTest(PyObject *obj, PyTypeObject *type) {
    if (!type) {
        PyErr_Format(PyExc_SystemError, "Missing type object");
        return 0;
    }
    if (obj == Py_None || PyObject_TypeCheck(obj, type))
        return 1;
    PyErr_Format(PyExc_TypeError, "Cannot convert %s to %s",
        obj->ob_type->tp_name, type->tp_name);
    return 0;
}

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb) {
    Py_XINCREF(type);
    Py_XINCREF(value);
    Py_XINCREF(tb);
    /* First, check the traceback argument, replacing None with NULL. */
    if (tb == Py_None) {
        Py_DECREF(tb);
        tb = 0;
    }
    else if (tb != NULL && !PyTraceBack_Check(tb)) {
        PyErr_SetString(PyExc_TypeError,
            "raise: arg 3 must be a traceback or None");
        goto raise_error;
    }
    /* Next, replace a missing value with None */
    if (value == NULL) {
        value = Py_None;
        Py_INCREF(value);
    }
    /* Next, repeatedly, replace a tuple exception with its first item */
    while (PyTuple_Check(type) && PyTuple_Size(type) > 0) {
        PyObject *tmp = type;
        type = PyTuple_GET_ITEM(type, 0);
        Py_INCREF(type);
        Py_DECREF(tmp);
    }
    if (PyString_Check(type))
        ;
    else if (PyClass_Check(type))
        ; /*PyErr_NormalizeException(&type, &value, &tb);*/
    else if (PyInstance_Check(type)) {
        /* Raising an instance.  The value should be a dummy. */
        if (value != Py_None) {
            PyErr_SetString(PyExc_TypeError,
              "instance exception may not have a separate value");
            goto raise_error;
        }
        else {
            /* Normalize to raise <class>, <instance> */
            Py_DECREF(value);
            value = type;
            type = (PyObject*) ((PyInstanceObject*)type)->in_class;
            Py_INCREF(type);
        }
    }
    else {
        /* Not something you can raise.  You get an exception
           anyway, just not what you specified :-) */
        PyErr_Format(PyExc_TypeError,
                 "exceptions must be strings, classes, or "
                 "instances, not %s", type->ob_type->tp_name);
        goto raise_error;
    }
    PyErr_Restore(type, value, tb);
    return;
raise_error:
    Py_XDECREF(value);
    Py_XDECREF(type);
    Py_XDECREF(tb);
    return;
}

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t) {
    while (t->p) {
        *t->p = PyString_InternFromString(t->s);
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

static PyTypeObject *__Pyx_ImportType(char *module_name, char *class_name, 
    long size) 
{
    PyObject *py_module_name = 0;
    PyObject *py_class_name = 0;
    PyObject *py_name_list = 0;
    PyObject *py_module = 0;
    PyObject *result = 0;
    
    py_module_name = PyString_FromString(module_name);
    if (!py_module_name)
        goto bad;
    py_class_name = PyString_FromString(class_name);
    if (!py_class_name)
        goto bad;
    py_name_list = PyList_New(1);
    if (!py_name_list)
        goto bad;
    Py_INCREF(py_class_name);
    if (PyList_SetItem(py_name_list, 0, py_class_name) < 0)
        goto bad;
    py_module = __Pyx_Import(py_module_name, py_name_list);
    if (!py_module)
        goto bad;
    result = PyObject_GetAttr(py_module, py_class_name);
    if (!result)
        goto bad;
    if (!PyType_Check(result)) {
        PyErr_Format(PyExc_TypeError, 
            "%s.%s is not a type object",
            module_name, class_name);
        goto bad;
    }
    if (((PyTypeObject *)result)->tp_basicsize != size) {
        PyErr_Format(PyExc_ValueError, 
            "%s.%s does not appear to be the correct type object",
            module_name, class_name);
        goto bad;
    }
    goto done;
bad:
    Py_XDECREF(result);
    result = 0;
done:
    Py_XDECREF(py_module_name);
    Py_XDECREF(py_class_name);
    Py_XDECREF(py_name_list);
    return (PyTypeObject *)result;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_tuple = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;
    
    py_srcfile = PyString_FromString(__pyx_filename);
    if (!py_srcfile) goto bad;
    py_funcname = PyString_FromString(funcname);
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    empty_tuple = PyTuple_New(0);
    if (!empty_tuple) goto bad;
    empty_string = PyString_FromString("");
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        empty_tuple,  /*PyObject *consts,*/
        empty_tuple,  /*PyObject *names,*/
        empty_tuple,  /*PyObject *varnames,*/
        empty_tuple,  /*PyObject *freevars,*/
        empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_tuple);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}
