python_sources = [
'ace_mbondi3.parm7',
'ace_mbondi3.negative.parm7',
'ace_mbondi3.nc',
'ace_mbondi3.error3.parm7',
'ace_mbondi3.error2.parm7',
'ace_mbondi3.error1.parm7',
'anti.top',
'ala.ff19SB.OPC.parm7.bz2',
'ache.prmtop',
'ache.mdcrd.bz2',
'ache.mdcrd',
'ace_tip3p.parm7',
'ace_tip3p.nc',
'anti_md1.mdcrd.bz2',
'bala.prmtop',
'bala.ncdf',
'bala.trj',
'test.inpcrd',
'posfor.top',
'posfor.ncdf',
'parmed_fad.prmtop',
'parmed_ala2_solv.rst7',
'parmed_ala2_solv.parm7',
'cpptraj_traj.prmtop',
'cpptraj_traj.nc',
'chitosan.prmtop',
'capped-ala.prmtop',
'capped-ala.mdcrd.bz2',
'tz2.truncoct.parm7.bz2',
'tz2.truncoct.nc',
'ache_chainid.prmtop.bz2',
'ache_chainid.error5.prmtop.bz2',
'ace_mbondi3.error4.parm7',
'__init__.py',
]

py3.install_sources(
  python_sources,
  subdir: 'MDAnalysisTests/data/Amber'
)
