python_sources = [
'chain_initial.data',
'chain_dump_2.lammpstrj',
'chain_dump_1.lammpstrj',
'a_lot_of_bond_types.data',
'albite_triclinic.dump',
'albite_triclinic.data',
'cnt-hexagonal-class1.data2',
'cnt-hexagonal-class1.data',
'ifabp_apo_100mM.data.bz2',
'hydrogen-class1.data2',
'hydrogen-class1.data',
'deletedatoms.data',
'datatest.trz',
'datatest.data',
'pairij_coeffs.data.bz2',
'mini.data',
'image_vf.lammpstrj',
'image_vf.data',
'ifabp_apo_100mM.in',
'ifabp_apo_100mM.dcd',
'wat.lammpstrj_long.bz2',
'wat.lammpstrj.bz2',
'spce_no_coords.lammpstrj.bz2',
'spce_all_coords.lammpstrj.bz2',
'__init__.py',
'additional_columns.lammpstrj',
'additional_columns.data',
'nomass_elemx.lammpstrj',
'mass_q_elem.lammpstrj',
]

py3.install_sources(
  python_sources,
  subdir: 'MDAnalysisTests/data/lammps'
)

