package:
  name: mdanalysis
  # This has to be changed after a release
  version: "0.19.1dev"

source:
   git_url: https://github.com/MDAnalysis/mdanalysis
   git_branch: develop
   # git_tag: release-0.15.0

# specify the subversion of the conda package. Defaults to 0. If you make
# changes to the conda package alone with out an increase in the source package
# version increase this number. Should be reset to 0 after a new release
build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - numpy x.x
    - cython

  run:
    - python
    - biopython
    - joblib
    - scipy
    - griddataformats
    - networkx
    - matplotlib
    - mock
    - seaborn
    - six
    - psutil
    - netcdf4
    - mmtf-python
    - scikit-learn
    - funcsigs

test:
  imports:
    - MDAnalysis
    - MDAnalysis.analysis
    - MDAnalysis.lib.c_distances_openmp
    - MDAnalysis.lib.c_distances

  commands:
    - python -c 'import MDAnalysisTests; MDAnalysisTests.run(label="full", extra_argv=["-v", "--no-open-files"])'

about:
  home: https://www.mdanalysis.org
  license: GPLv2
  license_file: package/LICENSE
  summary: 'MDAnalysis is a Python library to analyze molecular dynamics trajectories.'
