name: 'build-src'
description: 'make source builds for CI'
inputs:
  build-tests:
    description: 'build MDA tests'
    required: true
    default: true
  build-docs:
    description: 'build MDA docs'
    required: true
    default: false
  isolation:
    descriptions: 'use build isolation for pip installs'
    required: true
    default: false


runs:
  using: "composite"
  steps:
    - name: echo_inputs
      shell: bash -l {0}
      run: |
        echo ${{ inputs.build-tests }}
        echo ${{ inputs.build-docs }}
        echo ${{ inputs.isolation }}

    - name: check_setup
      shell: bash -l {0}
      run: |
        # Check OS and python setup prior to builds
        echo "OS: ${OS_NAME}"
        which python
        which pip
        pip list
        conda info
        conda list

    - name: build_mda_main
      shell: bash -l {0}
      run: |
        if [ ${{ input.isolation }} == 'true' ]; then
          $BUILD_FLAGS="--no-build-isolation"
        fi
        # install instead of develop would reduce coverage (for .pyx files)
        python -m pip install --no-build-isolation -v -e ./package

    - name: build_mda_tests
      if: ${{ inputs.build-tests == 'true' }}
      shell: bash -l {0}
      run: |
        if [ ${{ input.isolation }} == 'true' ]; then
          $BUILD_FLAGS="--no-build-isolation"
        fi
        python -m pip install --no-build-isolation -v -e ./testsuite

    - name: build_docs
      if: ${{ inputs.build-docs == 'true' }}
      shell: bash -l {0}
      run: |
        cd package && python setup.py build_sphinx -E --keep-going
