py3.extension_module('timestep',
  [cython_gen_cpp.process('timestep.pyx')],
  cpp_args: cython_cpp_args,
  dependencies: np_dep,
  install: true,
  subdir: 'MDAnalysis/coordinates'
)

py3.install_sources([
    'CRD.py',
    'DMS.py',
    'FHIAIMS.py',
    'NAMDBIN.py',
    'ParmEd.py',
    'TNG.py',
    'core.py',
    'null.py',
    'DLPoly.py',
    'GRO.py',
    'GSD.py',
    'INPCRD.py',
    'MMTF.py',
    'PDBQT.py',
    'PQR.py',
    'TRJ.py',
    'TRZ.py',
    'XDR.py',
    'TRC.py',
    'base.py',
    'DCD.py',
    'GMS.py',
    'H5MD.py',
    'LAMMPS.py',
    'MOL2.py',
    'PDB.py',
    'TPR.py',
    'TRR.py',
    'TXYZ.py',
    'XTC.py',
    'XYZ.py',
    '__init__.py',
    'chain.py',
    'chemfiles.py',
    'memory.py',
  ],
  subdir: 'MDAnalysis/coordinates'
)
