python_sources = [
'__init__.py',
'util.py',
'test_wrap.py',
'test_updating_atomgroup.py',
'test_unwrap.py',
'test_topology.py',
'test_topologyobjects.py',
'test_topologyattrs.py',
'test_segment.py',
'test_segmentgroup.py',
'test_residue.py',
'test_residuegroup.py',
'test_requires.py',
'test_index_dtype.py',
'test_group_traj_access.py',
'test_groups.py',
'test_fragments.py',
'test_copying.py',
'test_atom.py',
'test_atomgroup.py',
'test_accumulate.py',
'test_accessors.py',
'test_universe.py',
'test_atomselections.py',
]

py3.install_sources(
  python_sources,
  subdir: 'MDAnalysisTests/core'
)


