py3.install_sources([
    'tables.py',
    'CRDParser.py',
    'DLPolyParser.py',
    'DMSParser.py',
    'ExtendedPDBParser.py',
    'FHIAIMSParser.py',
    'GMSParser.py',
    'GROParser.py',
    'GSDParser.py',
    'HoomdXMLParser.py',
    'ITPParser.py',
    'MOL2Parser.py',
    'MinimalParser.py',
    'PSFParser.py',
    'ParmEdParser.py',
    'TXYZParser.py',
    'XYZParser.py',
    'core.py',
    'guessers.py',
    'TOPParser.py',
    'MMTFParser.py',
    'PDBParser.py',
    'PDBQTParser.py',
    'PQRParser.py',
    '__init__.py',
    'LAMMPSParser.py',
    'TPRParser.py',
    'base.py',
  ],
  subdir: 'MDAnalysis/topology'
)

subdir('tpr')
