python_sources = [
'gromos11_truncOcta_vac.trc.gz',
'gromos11_triclinic_solv.trc.gz',
'gromos11_traj_vac.pdb.gz',
'gromos11_traj_vac_2.trc.gz',
'gromos11_traj_vac_1.trc.gz',
'gromos11_traj_solv.trc.gz',
'gromos11_traj_solv.pdb.gz',
'gromos11_genbox_origin.trc.gz',
'gromos11_genbox_euler.trc.gz',
'gromos11_empty.trc',
'gromos11_cluster_vac.trj.gz',
'__init__.py',
'gromos11_traj_vac_1_whitespace.trc.gz',
'gromos11_traj_vac_1_missing_pos.trc.gz',
'gromos11_traj_vac_1_extra_pos.trc.gz',
]

py3.install_sources(
  python_sources,
  subdir: 'MDAnalysisTests/data/gromos11'
)

