python_sources = [
'__init__.py',
'test_modelling.py',
'test_meta.py',
'test_log.py',
'test_imports.py',
'test_failure.py',
'test_datafiles.py',
'test_authors.py',
'test_units.py',
'test_transformations.py',
'test_streamio.py',
'test_selections.py',
'test_qcprot.py',
'test_pickleio.py',
'test_persistence.py',
'test_duecredit.py',
]

py3.install_sources(
  python_sources,
  subdir: 'MDAnalysisTests/utils'
)


