py3.install_sources([
    '__init__.py',
    'test_distances.py',
    'test_dihedrals.py',
    'test_diffusionmap.py',
    'test_dielectric.py',
    'test_density.py',
    'test_data.py',
    'test_contacts.py',
    'test_bat.py',
    'test_backends.py',
    'test_atomicdistances.py',
    'test_align.py',
    'test_wbridge.py',
    'test_rms.py',
    'test_results.py',
    'test_pca.py',
    'test_nuclinfo.py',
    'test_nucleicacids.py',
    'test_leaflet.py',
    'test_hydrogenbondautocorrel.py',
    'test_hydrogenbondautocorrel_deprecated.py',
    'test_helix_analysis.py',
    'test_encore.py',
    'test_dssp.py',
    'test_waterdynamics.py',
    'test_psa.py',
    'test_hole2.py',
    'test_lineardensity.py',
    'test_hydrogenbonds_analysis.py',
    'test_gnm.py',
    'test_base.py',
    'test_persistencelength.py',
    'test_msd.py',
    'test_rdf_s.py',
    'test_rdf.py',
    'conftest.py',
  ],
  subdir: 'MDAnalysisTests/analysis'
)
