# $Id$
"""MDAnalysis is a python framework to analyze molecular dynamics
trajectories generated by Charmm, NAMD, or LAMMPS (Gromacs support is
in the working...).

It allows one to read molecular dynamics trajectories and access the
atomic coordinates through numpy arrays. This provides an extremely
flexible and relatively fast framework for complex analysis tasks. In
addition, Charmm-style atom selection commands are
implemented. Trajectories can also be manipulated (for instance, fit
to a reference structure) and written out.

Code and documentation are hosted at http://code.google.com/p/mdanalysis/

Help is also available through the mailinglist at
http://groups.google.com/group/mdnalysis-discussion

Please report bugs and feature requests through the issue tracker at
http://code.google.com/p/mdanalysis/issues/ 
"""

# These imports make everything appear to the user as if we still had
# the 0.5.1 module layout.
__all__ = ['AtomGroup','Selection','Timeseries','distances','rms_fitting',
           'DCD','PDB']
from core import AtomGroup,Selection,Timeseries,distances,rms_fitting
from coordinates import DCD,PDB

# Bring some often used objects into the current namespace
Universe = core.AtomGroup.Universe
collection = core.Timeseries.TimeseriesCollection()

