python_sources = [
'README',
'__init__.py',
'test_xyz.py',
'test_xpdb.py',
'test_txyz.py',
'test_top.py',
'test_topology_str_types.py',
'test_topology_base.py',
'test_tables.py',
'test_psf.py',
'test_pqr.py',
'test_pdbqt.py',
'test_mol2.py',
'test_mmtf.py',
'test_minimal.py',
'test_itp.py',
'test_hoomdxml.py',
'test_guessers.py',
'test_gsd.py',
'test_gro.py',
'test_gms.py',
'test_fhiaims.py',
'test_dms.py',
'test_dlpoly.py',
'test_crd.py',
'test_altloc.py',
'base.py',
'test_pdb.py',
'test_lammpsdata.py',
'test_tprparser.py',
]

py3.install_sources(
  python_sources,
  subdir: 'MDAnalysisTests/topology'
)


