name: mdanalysis-dev-intel
channels:
  - conda-forge
  - defaults
dependencies:
  - python >=3.9.2
  - biopython >=1.80
  - chemfiles >=0.10
  - cython >=0.28
  - fasteners
  - griddataformats >=0.4.0
  - gsd >3.0.0
  - joblib >=0.12
  - h5py >=2.10
  - hole2
  - matplotlib >=1.5.1
  - mmtf-python >=1.0.0
  - openmm
  - netcdf4 >=1.0
  - networkx >=2.0
  - numpy >=1.21.0
  - packaging
  - parmed
  - pyedr >=0.7.0
  - pytng >=0.2.3
  - rdkit >=2020.03.1
  - scikit-learn
  - seaborn
  - scipy >=1.5.0
  - threadpoolctl
  - tidynamics >=1.0.0
  - tqdm >=4.43.0

  # docs
  - sphinx <7.0
  - pybtex
  - pybtex-docutils
  - sphinxcontrib-bibtex
  - sphinx_rtd_theme
  - sphinx-sitemap
  - pip:
      - msmb_theme ==1.2.0
