[build-system]
# Minimum requirements for the build system to execute
requires = [
    "Cython>=0.28",
    "packaging",
    # numpy requirement for wheel builds for distribution on PyPI - building
    # against 2.x yields wheels that are also compatible with numpy 1.x at
    # runtime.
    # Note that building against numpy 1.x works fine too - users and
    # redistributors can do this by installing the numpy version they like and
    # disabling build isolation.
    "numpy>=2.0.0",
    # Set to minimum version of setuptools that allows pyproject.toml
    "setuptools >= 40.9.0",
    "wheel",
]
build-backend = "setuptools.build_meta"

[project]
name = "MDAnalysis"
dynamic = ['version', 'readme']
license = {file = "LICENSE"}
description = "An object-oriented toolkit to analyze molecular dynamics trajectories."
authors = [
    {name = 'MDAnalysis Development Team', email = 'mdanalysis@numfocus.org'}
]
maintainers = [
    {name = 'MDAnalysis Core Developers', email = 'mdanalysis@numfocus.org'}
]
requires-python = ">=3.10"
dependencies = [
    'numpy>=1.23.2',
    'GridDataFormats>=0.4.0',
    'mmtf-python>=1.0.0',
    'joblib>=0.12',
    'scipy>=1.5.0',
    'matplotlib>=1.5.1',
    'tqdm>=4.43.0',
    'threadpoolctl',
    'packaging',
    'fasteners',
    'mda-xdrlib',
    'waterdynamics',
    'pathsimanalysis',
    'mdahole2',
]
keywords = [
    "python", "science", "chemistry", "biophysics", "molecular-dynamics",
    "computational-chemistry", "molecular-simulation", "analysis",
    "trajectory-analysis",
]
classifiers = [
    'Development Status :: 6 - Mature',
    'Environment :: Console',
    'Intended Audience :: Science/Research',
    'License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)',
    'Operating System :: POSIX',
    'Operating System :: MacOS :: MacOS X',
    'Operating System :: Microsoft :: Windows',
    'Programming Language :: Python',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3.11',
    'Programming Language :: Python :: 3.12',
    'Programming Language :: C',
    'Topic :: Scientific/Engineering',
    'Topic :: Scientific/Engineering :: Bio-Informatics',
    'Topic :: Scientific/Engineering :: Chemistry',
    'Topic :: Software Development :: Libraries :: Python Modules',
]

[project.optional-dependencies]
extra_formats = [
    "netCDF4>=1.0",
    "h5py>=2.10",
    "chemfiles>=0.10",
    "parmed",
    "pyedr>=0.7.0",
    "pytng>=0.2.3",
    "gsd>3.0.0",
    "rdkit>=2020.03.1",
]
analysis = [
    "biopython>=1.80",
    "seaborn",
    "scikit-learn",
    "tidynamics>=1.0.0",
    'networkx>=2.0',
]
doc = [
    "sphinx",
    "sphinx-sitemap",
    "mdanalysis-sphinx-theme>=1.3.0",
    "sphinxcontrib-bibtex",
    "pybtex",
    "pybtex-docutils",
]
parallel = [
    "dask",
]

[project.urls]
Homepage = "https://www.mdanalysis.org"
Download = "https://github.com/MDAnalysis/mdanalysis/releases"
Documentation = "https://docs.mdanalysis.org/"
"User Guide" = "https://userguide.mdanalysis.org/"
"Issue Tracker" = "https://github.com/mdanalysis/mdanalysis/issues"
"Github Discussions" = "https://github.com/MDAnalysis/mdanalysis/discussions"
Discord = "https://discord.com/channels/807348386012987462/"
Blog = "https://www.mdanalysis.org/blog/"
Source = 'https://github.com/mdanalysis/mdanalysis'

[tool.setuptools]
# as a zipped egg the *.so files are not found (at
# least in Ubuntu/Linux)
zip-safe = false

[tool.setuptools.packages]
find = {}

[tool.setuptools.package-data]
MDAnalysis = [
    'analysis/data/*.npy',
]

[tool.black]
line-length = 79
target-version = ['py310', 'py311', 'py312', 'py313']
include = '''
(
tables\.py
| due\.py
| setup\.py
| MDAnalysis/auxiliary/.*\.py
| MDAnalysis/visualization/.*\.py
| MDAnalysis/lib/.*\.py^
| MDAnalysis/transformations/.*\.py
)
'''
extend-exclude = '''
(
__pycache__
| MDAnalysis/analysis/align\.py
| MDAnalysis/analysis/base\.py
| MDAnalysis/analysis/encore/clustering/cluster\.py
| MDAnalysis/analysis/encore/dimensionality_reduction/reduce_dimensionality\.py
| MDAnalysis/analysis/encore/similarity\.py
| MDAnalysis/analysis/helix_analysis\.py
| MDAnalysis/core/universe\.py
| MDAnalysis/topology/ITPParser\.py
| MDAnalysis/analysis/atomicdistances\.py
| MDAnalysis/lib/NeighborSearch\.py
| MDAnalysis/lib/__init__\.py
| MDAnalysis/lib/_distopia\.py
| MDAnalysis/lib/correlations\.py
| MDAnalysis/lib/distances\.py
| MDAnalysis/lib/formats/__init__\.py
| MDAnalysis/lib/log\.py
| MDAnalysis/lib/mdamath\.py
| MDAnalysis/lib/picklable_file_io\.py
| MDAnalysis/lib/pkdtree\.py
| MDAnalysis/lib/transformations\.py
| MDAnalysis/lib/util\.py
| MDAnalysis/coordinates/XDR\.py
| MDAnalysis/core/selection\.py
| MDAnalysis/coordinates/XYZ\.py
| MDAnalysis/analysis/diffusionmap\.py
| MDAnalysis/analysis/align\.py
| MDAnalysis/lib/_distopia\.py
| MDAnalysis/lib/distances\.py
| MDAnalysis/analysis/density\.py
| MDAnalysis/analysis/nucleicacids\.py
| MDAnalysis/analysis/dasktimeseries\.py
| MDAnalysis/coordinates/H5MD\.py
| MDAnalysis/coordinates/MMCIF\.py
| MDAnalysis/coordinates/__init__\.py
| MDAnalysis/topology/MMCIFParser\.py
| MDAnalysis/topology/PDBParser\.py
| MDAnalysis/topology/__init__\.py
| MDAnalysis/topology/tpr/utils\.py
| MDAnalysis/coordinates/CIF\.py
| MDAnalysis/coordinates/PDBx\.py
| MDAnalysis/coordinates/__init__\.py
| MDAnalysis/topology/PDBxParser\.py
| MDAnalysis/topology/__init__\.py
| MDAnalysis/core/groups\.py
| MDAnalysis/coordinates/base\.py
| MDAnalysis/core/universe\.py
| MDAnalysis/topology/base\.py
| MDAnalysis/analysis/hydrogenbonds/hbond_analysis\.py
| MDAnalysis/auxiliary/EDR\.py
| MDAnalysis/auxiliary/__init__\.py
| MDAnalysis/coordinates/base\.py
| MDAnalysis/coordinates/memory\.py
| .pylintrc
| MDAnalysis/analysis/bat\.py
| MDAnalysis/analysis/contacts\.py
| MDAnalysis/analysis/density\.py
| MDAnalysis/analysis/distances\.py
| MDAnalysis/analysis/encore/confdistmatrix\.py
| MDAnalysis/analysis/encore/dimensionality_reduction/DimensionalityReductionMethod\.py
| MDAnalysis/analysis/encore/similarity\.py
| MDAnalysis/analysis/encore/utils\.py
| MDAnalysis/analysis/hydrogenbonds/wbridge_analysis\.py
| MDAnalysis/analysis/legacy/x3dna\.py
| MDAnalysis/analysis/lineardensity\.py
| MDAnalysis/analysis/nucleicacids\.py
| MDAnalysis/analysis/psa\.py
| MDAnalysis/analysis/rms\.py
| MDAnalysis/analysis/waterdynamics\.py
| MDAnalysis/auxiliary/base\.py
| MDAnalysis/converters/ParmEd\.py
| MDAnalysis/coordinates/DCD\.py
| MDAnalysis/coordinates/DLPoly\.py
| MDAnalysis/coordinates/DMS\.py
| MDAnalysis/coordinates/FHIAIMS\.py
| MDAnalysis/coordinates/GRO\.py
| MDAnalysis/coordinates/H5MD\.py
| MDAnalysis/coordinates/PDB\.py
| MDAnalysis/coordinates/PQR\.py
| MDAnalysis/coordinates/ParmEd\.py
| MDAnalysis/coordinates/TRR\.py
| MDAnalysis/coordinates/TRZ\.py
| MDAnalysis/coordinates/TXYZ\.py
| MDAnalysis/coordinates/XTC\.py
| MDAnalysis/coordinates/base\.py
| MDAnalysis/coordinates/core\.py
| MDAnalysis/coordinates/memory\.py
| MDAnalysis/coordinates/timestep.pyx
| MDAnalysis/core/groups\.py
| MDAnalysis/core/topology\.py
| MDAnalysis/core/topologyattrs\.py
| MDAnalysis/core/topologyobjects\.py
| MDAnalysis/core/universe\.py
| MDAnalysis/due\.py
| MDAnalysis/lib/distances\.py
| MDAnalysis/lib/log\.py
| MDAnalysis/lib/mdamath\.py
| MDAnalysis/lib/pkdtree\.py
| MDAnalysis/lib/transformations\.py
| MDAnalysis/lib/util\.py
| MDAnalysis/selections/base\.py
| MDAnalysis/topology/GSDParser\.py
| MDAnalysis/topology/HoomdXMLParser\.py
| MDAnalysis/topology/ITPParser\.py
| MDAnalysis/topology/LAMMPSParser\.py
| MDAnalysis/topology/PSFParser\.py
| MDAnalysis/topology/ParmEdParser\.py
| MDAnalysis/topology/TPRParser\.py
| MDAnalysis/topology/base\.py
| MDAnalysis/topology/core\.py
| MDAnalysis/visualization/streamlines\.py
| MDAnalysis/visualization/streamlines_3D\.py
| MDAnalysis/coordinates/timestep.pyx
| MDAnalysis/analysis/sasa\.py
| MDAnalysis/analysis/align\.py
| MDAnalysis/lib/util\.py
| MDAnalysis/coordinates/DCD\.py
| MDAnalysis/coordinates/DLPoly\.py
| MDAnalysis/coordinates/GMS\.py
| MDAnalysis/coordinates/MOL2\.py
| MDAnalysis/coordinates/PDB\.py
| MDAnalysis/coordinates/TRJ\.py
| MDAnalysis/coordinates/TRR\.py
| MDAnalysis/coordinates/TRZ\.py
| MDAnalysis/coordinates/TXYZ\.py
| MDAnalysis/coordinates/XTC\.py
| MDAnalysis/coordinates/XYZ\.py
| MDAnalysis/coordinates/base\.py
| MDAnalysis/coordinates/chain\.py
| MDAnalysis/coordinates/chemfiles\.py
| MDAnalysis/coordinates/memory\.py
| MDAnalysis/core/groups\.py
| MDAnalysis/core/selection\.py
| doc/sphinx/source/conf\.py
| MDAnalysis/topology/ITPParser\.py
| MDAnalysis/converters/RDKit\.py
| MDAnalysis/converters/RDKitInferring\.py
| MDAnalysis/converters/__init__\.py
| MDAnalysis/coordinates/PDBx\.py
| MDAnalysis/topology/PDBxParser\.py
| MDAnalysis/core/selection\.py
| MDAnalysis/coordinates/DDC\.py
| MDAnalysis/coordinates/DDCMD\.py
| MDAnalysis/coordinates/DDCMDTAR\.py
| MDAnalysis/coordinates/__init__\.py
| MDAnalysis/topology/tpr/obj\.py
| MDAnalysis/topology/tpr/utils\.py
| MDAnalysis/core/universe\.py
| MDAnalysis/analysis/base\.py
| MDAnalysis/coordinates/INPCRD\.py
| MDAnalysis/coordinates/__init__\.py
| MDAnalysis/units\.py
| MDAnalysis/analysis/msd\.py
| MDAnalysis/__init__\.py
| MDAnalysis/analysis/bat\.py
| MDAnalysis/converters/OpenMMParser\.py
| MDAnalysis/converters/ParmEd\.py
| MDAnalysis/converters/ParmEdParser\.py
| MDAnalysis/converters/RDKit\.py
| MDAnalysis/converters/RDKitParser\.py
| MDAnalysis/coordinates/PDB\.py
| MDAnalysis/core/groups\.py
| MDAnalysis/core/topologyattrs\.py
| MDAnalysis/core/universe\.py
| MDAnalysis/guesser/__init__\.py
| MDAnalysis/guesser/base\.py
| MDAnalysis/guesser/default_guesser\.py
| MDAnalysis/guesser/pdb_guesser\.py
| MDAnalysis/guesser/pdb_tables\.py
| MDAnalysis/guesser/tables\.py
| MDAnalysis/topology/CRDParser\.py
| MDAnalysis/topology/DLPolyParser\.py
| MDAnalysis/topology/DMSParser\.py
| MDAnalysis/topology/ExtendedPDBParser\.py
| MDAnalysis/topology/FHIAIMSParser\.py
| MDAnalysis/topology/GMSParser\.py
| MDAnalysis/topology/GROParser\.py
| MDAnalysis/topology/GSDParser\.py
| MDAnalysis/topology/HoomdXMLParser\.py
| MDAnalysis/topology/ITPParser\.py
| MDAnalysis/topology/LAMMPSParser\.py
| MDAnalysis/topology/MMTFParser\.py
| MDAnalysis/topology/MOL2Parser\.py
| MDAnalysis/topology/PDBParser\.py
| MDAnalysis/topology/PDBQTParser\.py
| MDAnalysis/topology/PQRParser\.py
| MDAnalysis/topology/PSFParser\.py
| MDAnalysis/topology/TOPParser\.py
| MDAnalysis/topology/TPRParser\.py
| MDAnalysis/topology/TXYZParser\.py
| MDAnalysis/topology/XYZParser\.py
| MDAnalysis/topology/__init__\.py
| MDAnalysis/topology/base\.py
| MDAnalysis/topology/core\.py
| MDAnalysis/topology/tpr/obj\.py
| MDAnalysis/coordinates/CRD\.py
| MDAnalysis/coordinates/DCD\.py
| MDAnalysis/coordinates/FHIAIMS\.py
| MDAnalysis/coordinates/GRO\.py
| MDAnalysis/coordinates/H5MD\.py
| MDAnalysis/coordinates/MOL2\.py
| MDAnalysis/coordinates/NAMDBIN\.py
| MDAnalysis/coordinates/PDB\.py
| MDAnalysis/coordinates/PDBQT\.py
| MDAnalysis/coordinates/PQR\.py
| MDAnalysis/coordinates/TRJ\.py
| MDAnalysis/coordinates/TRZ\.py
| MDAnalysis/coordinates/XDR\.py
| MDAnalysis/coordinates/XTC\.py
| MDAnalysis/coordinates/XYZ\.py
| MDAnalysis/coordinates/base\.py
| MDAnalysis/coordinates/chemfiles\.py
| MDAnalysis/coordinates/core\.py
| MDAnalysis/coordinates/null\.py
| MDAnalysis/auxiliary/NumPy\.py
| MDAnalysis/coordinates/XYZ\.py
| MDAnalysis/converters/OpenMMParser\.py
| MDAnalysis/converters/ParmEdParser\.py
| MDAnalysis/converters/RDKitParser\.py
| MDAnalysis/auxiliary/XVG\.py
| MDAnalysis/auxiliary/core\.py
| MDAnalysis/visualization/streamlines\.py
| MDAnalysis/visualization/streamlines_3D\.py
| MDAnalysis/core/__init__\.py
| MDAnalysis/core/bondtable.pyx
| MDAnalysis/core/topologyattrs\.py
| MDAnalysis/lib/_cutil.pyx
| setup\.py
| MDAnalysis/analysis/align\.py
| MDAnalysis/analysis/dielectric\.py
| MDAnalysis/analysis/diffusionmap\.py
| MDAnalysis/analysis/encore/similarity\.py
| MDAnalysis/analysis/helix_analysis\.py
| MDAnalysis/analysis/hydrogenbonds/hbond_analysis\.py
| MDAnalysis/analysis/leaflet\.py
| MDAnalysis/analysis/msd\.py
| MDAnalysis/analysis/pca\.py
| MDAnalysis/analysis/rms\.py
| MDAnalysis/analysis/waterdynamics\.py
| MDAnalysis/core/topologyattrs\.py
| MDAnalysis/lib/qcprot.pyx
| MDAnalysis/visualization/streamlines\.py
| MDAnalysis/topology/CRDParser\.py
| MDAnalysis/topology/DLPolyParser\.py
| MDAnalysis/topology/DMSParser\.py
| MDAnalysis/topology/FHIAIMSParser\.py
| MDAnalysis/topology/GMSParser\.py
| MDAnalysis/topology/GROParser\.py
| MDAnalysis/topology/GSDParser\.py
| MDAnalysis/topology/LAMMPSParser\.py
| MDAnalysis/topology/MOL2Parser\.py
| MDAnalysis/topology/MinimalParser\.py
| MDAnalysis/topology/PDBParser\.py
| MDAnalysis/topology/PDBQTParser\.py
| MDAnalysis/topology/PQRParser\.py
| MDAnalysis/topology/TOPParser\.py
| MDAnalysis/topology/TPRParser\.py
| MDAnalysis/topology/TXYZParser\.py
| MDAnalysis/topology/XYZParser\.py
| MDAnalysis/topology/base\.py
| MDAnalysis/analysis/align\.py
| MDAnalysis/analysis/bat\.py
| MDAnalysis/analysis/contacts\.py
| MDAnalysis/analysis/density\.py
| MDAnalysis/analysis/dielectric\.py
| MDAnalysis/analysis/diffusionmap\.py
| MDAnalysis/analysis/dihedrals\.py
| MDAnalysis/analysis/distances\.py
| MDAnalysis/analysis/gnm\.py
| MDAnalysis/analysis/leaflet\.py
| MDAnalysis/analysis/lineardensity\.py
| MDAnalysis/analysis/msd\.py
| MDAnalysis/analysis/nuclinfo\.py
| MDAnalysis/analysis/polymer\.py
| MDAnalysis/core/_get_readers\.py
| MDAnalysis/core/accessors\.py
| MDAnalysis/topology/MOL2Parser\.py
| MDAnalysis/topology/PDBParser\.py
| MDAnalysis/topology/base\.py
| MDAnalysis/lib/mdamath\.py
| MDAnalysis/lib/util\.py
| MDAnalysis/lib/distances\.py
| MDAnalysis/lib/nsgrid.pyx
| MDAnalysis/coordinates/base\.py
| MDAnalysis/coordinates/chain\.py
| MDAnalysis/core/_get_readers\.py
| MDAnalysis/core/groups\.py
| MDAnalysis/core/topologyattrs\.py
| MDAnalysis/core/universe\.py
| MDAnalysis/lib/_cutil.pyx
| MDAnalysis/lib/util\.py
| MDAnalysis/core/groups\.py
| MDAnalysis/lib/distances\.py
| MDAnalysis/lib/mdamath\.py
| MDAnalysis/transformations/__init__\.py
| MDAnalysis/transformations/wrap\.py
| MDAnalysis/analysis/RDKit\.py
| MDAnalysis/analysis/__init__\.py
| MDAnalysis/__init__\.py
| MDAnalysis/visualization/RDKit\.py
| MDAnalysis/visualization/base\.py
)
'''
required-version = '24'
