name: readthedocs/preview

on:
  pull_request_target:
    types: [opened]
    branches:
      - develop

jobs:
  rtdpreview:
    if: "github.repository == 'MDAnalysis/mdanalysis'"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      pull-requests: write
    steps:
    - uses: readthedocs/actions/preview@v1
      with:
        project-slug: "mdanalysis"
